// ============================================================
// BEZMASAJIDLA.CZ — Restaurant & Recipe Data
// "Zelená Metropole" design system
// ============================================================

export type RestaurantType = "vegan" | "vegetarian" | "friendly" | "fastfood";

export type DietaryOption = "bezlepkové" | "raw" | "bio" | "bez-soji" | "bez-oriskove" | "whole-food" | "ayurvédské" | "makrobiotické" | "low-carb" | "high-protein";

export interface Restaurant {
  id: string;
  name: string;
  slug: string;
  type: RestaurantType;
  rating: number;
  reviewCount: number;
  isOpen: boolean;
  isPremium: boolean;
  address: string;
  district: string;
  phone?: string;
  website?: string;
  description: string;
  tags: string[];
  dietaryOptions: DietaryOption[];
  image: string;
  lat: number;
  lng: number;
  priceLevel: 1 | 2 | 3;
  hours?: string;
  shoppingCenter?: string;
  /** Vegetarian/vegan menu items for fast food chains */
  fastFoodItems?: FastFoodItem[];
}

export interface FastFoodItem {
  name: string;
  description: string;
  isVegan: boolean;
  price?: string;
  image?: string;
}

export interface RecipeImage {
  url: string;
  alt: string;
}

export interface Recipe {
  id: string;
  title: string;
  slug: string;
  category: string;
  prepTime: number;
  cookTime: number;
  servings: number;
  difficulty: "snadný" | "střední" | "náročný";
  image: string;
  images: RecipeImage[];
  description: string;
  tags: string[];
  isVegan: boolean;
}

const RESTAURANT_PLACEHOLDER = "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/restaurant-placeholder-NfsuHQoJhFmyxCXwn7EygE.webp";

export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "Shromaždiště",
    slug: "shromazdistepraha",
    type: "vegan",
    rating: 5.0,
    reviewCount: 223,
    isOpen: false,
    isPremium: true,
    address: "Krásova 13, Praha 3 — Žižkov",
    district: "Praha 3",
    phone: "+420 776 148 259",
    description: "Veganský gastropub specializovaný na veganizaci tradičních českých jídel. Také nabízí výběr naložených/špinavých hranolek. Nachází se v tradiční a rustikální české hospodě v Žižkově.",
    tags: ["Česká kuchyně", "Americká", "Fast food", "Pivo/Víno", "Evropská"],
    dietaryOptions: ["whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/shromazdiste-vegansky-gastropub-praha_a3a92b07.webp",
    lat: 50.0820,
    lng: 14.4501,
    priceLevel: 2,
    hours: "Po–Pá 11:00–22:00, So–Ne 12:00–22:00",
  },
  {
    id: "2",
    name: "Dosa Dosa",
    slug: "dosa-dosa",
    type: "vegan",
    rating: 5.0,
    reviewCount: 251,
    isOpen: false,
    isPremium: true,
    address: "Újezd 43, Praha 1 — Malá Strana",
    district: "Praha 1",
    phone: "+420 725 511 536",
    description: "Veganská jídelna/kavárna servírující dosy, indická a asijská jídla a dezerty. Nabízí také českou kuchyni jako součást denního menu.",
    tags: ["Indická", "Organická", "Thajská", "Asijská", "Pekárna", "Snídaně", "Bezlepková"],
    dietaryOptions: ["bezlepkové", "bio"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/dosa-dosa-veganska-indicka-restaurace-praha_abaf4fdb.webp",
    lat: 50.0833,
    lng: 14.4033,
    priceLevel: 2,
    hours: "Po–Ne 10:00–21:00",
  },
  {
    id: "3",
    name: "Share Sweet and Espresso Bar",
    slug: "share-sweet-espresso",
    type: "vegan",
    rating: 5.0,
    reviewCount: 334,
    isOpen: false,
    isPremium: false,
    address: "Revoluční 18, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 771 151 113",
    description: "Veganský sladký a espresso bar provozovaný restaurací Palo Verde. Servíruje kávu, svačiny, obědy a dorty. Nabízí catering, narozeninové a svatební dorty.",
    tags: ["Pekárna", "Catering", "Snídaně", "Rozvoz", "S sebou"],
    dietaryOptions: ["bez-soji"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/share-sweet-espresso-bar-veganska-kavarna-praha_4bf2fb66.webp",
    lat: 50.0897,
    lng: 14.4282,
    priceLevel: 1,
    hours: "Po–Pá 8:00–18:00, So 9:00–17:00",
  },
  {
    id: "4",
    name: "Chutnej",
    slug: "chutnej",
    type: "vegan",
    rating: 5.0,
    reviewCount: 335,
    isOpen: true,
    isPremium: true,
    address: "Letohradská 50, Praha 7 — Holešovice",
    district: "Praha 7",
    phone: "+420 222 250 724",
    description: "Rostlinná restaurace a kavárna poblíž Letenské pláně. Nabízí denní brunch, oběd a sdílené večerní menu. Má také dezerty včetně pečiva ze sesterského podniku Krafin.",
    tags: ["Italská", "Středomořská", "Pivo/Víno", "Snídaně", "S sebou"],
    dietaryOptions: ["whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/chutnej-rostlinna-restaurace-praha_b5acba19.webp",
    lat: 50.1012,
    lng: 14.4201,
    priceLevel: 2,
    hours: "Po–Pá 9:00–22:00, So–Ne 10:00–22:00",
  },
  {
    id: "5",
    name: "Eaternia",
    slug: "eaternia",
    type: "vegan",
    rating: 5.0,
    reviewCount: 150,
    isOpen: false,
    isPremium: false,
    address: "Nádražní 349/3, Praha 5 — Smíchov",
    district: "Praha 5",
    description: "Veganský podnik v budově bývalé sladovny mezi dvěma železničními mosty. Sezónní pokrmy z místních surovin. Burgery, hot dogy, tradiční česká kuchyně a saláty.",
    tags: ["Americká", "Mezinárodní", "Pivo/Víno", "Catering", "Rozvoz"],
    dietaryOptions: ["whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/eaternia-veganska-restaurace-praha_dc6d1126.webp",
    lat: 50.0701,
    lng: 14.4052,
    priceLevel: 2,
    hours: "Út–Ne 12:00–21:00",
  },
  {
    id: "6",
    name: "Palo Verde",
    slug: "palo-verde",
    type: "vegan",
    rating: 4.5,
    reviewCount: 676,
    isOpen: true,
    isPremium: true,
    address: "Žitná 45, Praha 2 — Nové Město",
    district: "Praha 2",
    phone: "+420 775 285 430",
    description: "Rostlinný bistro s organickými víny a kávovými nápoji, denním výběrem pečiva a croissantů a slanými pokrmy jako čerstvě vyrobené těstoviny, houbové ravioli, Beyond burger, fusion misky a španské tapas.",
    tags: ["Organická", "Pivo/Víno", "Pekárna", "Španělská", "Česká", "Fusion"],
    dietaryOptions: ["bio", "whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/palo-verde-rostlinne-bistro-praha_e6b9150c.webp",
    lat: 50.0762,
    lng: 14.4261,
    priceLevel: 2,
    hours: "Po–Pá 8:00–22:00, So–Ne 9:00–22:00",
  },
  {
    id: "7",
    name: "Střecha",
    slug: "strecha",
    type: "vegan",
    rating: 4.5,
    reviewCount: 797,
    isOpen: true,
    isPremium: false,
    address: "Křemencova 7, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 737 048 487",
    description: "Sociální podnik veganská restaurace zaměstnávající lidi bez domova a lidi po propuštění z vězení. Nabízí obědová menu, českou veganskou kuchyni, fair-trade kávu a alkoholické nápoje.",
    tags: ["Mezinárodní", "Pivo/Víno", "Catering", "Česká"],
    dietaryOptions: ["whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/strecha-veganska-restaurace-praha_729db866.webp",
    lat: 50.0788,
    lng: 14.4181,
    priceLevel: 1,
    hours: "Po–Pá 11:00–21:00",
  },
  {
    id: "8",
    name: "Koko Organic",
    slug: "koko-organic",
    type: "vegetarian",
    rating: 5.0,
    reviewCount: 58,
    isOpen: false,
    isPremium: false,
    address: "Biskupská 1753/5, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 777 583 999",
    description: "Vegetariánský vietnamský podnik. Servíruje rýži, nudle a pad thai pokrmy. Téměř všechna jídla jsou veganská.",
    tags: ["Asijská", "Vietnamská", "Organická"],
    dietaryOptions: ["bio", "bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/koko-organic-vegetarianska-vietnamska-praha_dcd9552c.webp",
    lat: 50.0901,
    lng: 14.4361,
    priceLevel: 1,
    hours: "Po–So 11:00–20:00",
  },
  {
    id: "9",
    name: "Linh — Not Just A Restaurant",
    slug: "linh-restaurant",
    type: "vegan",
    rating: 4.5,
    reviewCount: 454,
    isOpen: true,
    isPremium: true,
    address: "Mánesova 7, Praha 2 — Vinohrady",
    district: "Praha 2",
    phone: "+420 608 045 711",
    description: "Veganská vietnamská restaurace s pohádkovým interiérem. Nabízí rostlinná teplá jídla spolu s domácími dezerty, raw dorty, čerstvými džusy, smoothie a horkými nápoji. Pho, burgery, banh mi a pad thai.",
    tags: ["Mezinárodní", "Pivo/Víno", "Asijská", "Vietnamská", "Bezlepková"],
    dietaryOptions: ["bezlepkové", "raw"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/linh-veganska-vietnamska-restaurace-praha_5960b1ac.webp",
    lat: 50.0762,
    lng: 14.4401,
    priceLevel: 2,
    hours: "Po–Ne 11:00–22:00",
  },
  {
    id: "10",
    name: "Vegan's Prague",
    slug: "vegans-prague",
    type: "vegan",
    rating: 4.5,
    reviewCount: 884,
    isOpen: false,
    isPremium: false,
    address: "Nerudova 36, Praha 1 — Malá Strana",
    district: "Praha 1",
    phone: "+420 735 171 313",
    description: "Veganská restaurace v budově z 16. století poblíž Pražského hradu s terasou a výhledem, zal. 2016. Domácí česká a mezinárodní kuchyně. Guláš, raw čokoládový dort, bruschetta, sójové latte, cuketové lasagne.",
    tags: ["Mezinárodní", "Organická", "Raw", "Juice bar", "Česká"],
    dietaryOptions: ["raw", "bio"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegans-prague-veganska-restaurace-prazsky-hrad_3d77a5ec.webp",
    lat: 50.0882,
    lng: 14.4001,
    priceLevel: 2,
    hours: "Po–Ne 11:00–21:00",
  },
  {
    id: "11",
    name: "Belzepub",
    slug: "belzepub",
    type: "vegan",
    rating: 4.5,
    reviewCount: 185,
    isOpen: true,
    isPremium: false,
    address: "Záhřebská 6, Praha 2 — Vinohrady",
    district: "Praha 2",
    description: "Veganský bar a restaurace s výběrem piv, koktejlů a jídel. Přátelská atmosféra v srdci Vinohrad.",
    tags: ["Pivo/Víno", "Česká", "Mezinárodní"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/belzepub-vegansky-bar-praha_be8b8170.webp",
    lat: 50.0741,
    lng: 14.4421,
    priceLevel: 2,
    hours: "Po–Ne 16:00–01:00",
  },
  {
    id: "12",
    name: "Herbivore",
    slug: "herbivore",
    type: "vegan",
    rating: 4.5,
    reviewCount: 134,
    isOpen: false,
    isPremium: false,
    address: "Mánesova 59, Praha 2 — Vinohrady",
    district: "Praha 2",
    description: "Útulná veganská kavárna a bistro na Vinohradech. Domácí pečivo, snídaně, obědy a dezerty.",
    tags: ["Snídaně", "Pekárna", "Káva"],
    dietaryOptions: ["whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/herbivore-veganske-bistro-vinohrady_33d3ebdb.webp",
    lat: 50.0752,
    lng: 14.4441,
    priceLevel: 1,
    hours: "Po–Pá 8:00–18:00, So–Ne 9:00–17:00",
  },
  {
    id: "13",
    name: "Pastva",
    slug: "pastva",
    type: "vegan",
    rating: 4.5,
    reviewCount: 940,
    isOpen: true,
    isPremium: false,
    address: "Mánesova 87, Praha 2 — Vinohrady",
    district: "Praha 2",
    description: "Vegetariánská restaurace s důrazem na lokální a sezónní suroviny. Kreativní pokrmy inspirované českou i mezinárodní kuchyní.",
    tags: ["Česká", "Mezinárodní", "Organická", "Sezónní"],
    dietaryOptions: ["bio", "whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/pastva-vegetarianska-restaurace-praha_f522d5e0.webp",
    lat: 50.0731,
    lng: 14.4461,
    priceLevel: 2,
    hours: "Út–Ne 12:00–22:00",
  },
  {
    id: "14",
    name: "Onigirazu",
    slug: "onigirazu",
    type: "friendly",
    rating: 4.5,
    reviewCount: 69,
    isOpen: false,
    isPremium: false,
    address: "Korunní 18, Praha 2 — Vinohrady",
    district: "Praha 2",
    description: "Japonský podnik specializovaný na onigirazu — japonské sendviče z rýže. Mnoho veganských možností.",
    tags: ["Japonská", "Asijská", "S sebou"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/onigirazu-japonske-jidlo-praha_c417c073.webp",
    lat: 50.0771,
    lng: 14.4381,
    priceLevel: 1,
    hours: "Po–So 11:00–19:00",
  },
  {
    id: "15",
    name: "Loving Hut — Na Poříčí",
    slug: "loving-hut-na-porici",
    type: "vegan",
    rating: 4.5,
    reviewCount: 238,
    isOpen: false,
    isPremium: false,
    address: "Na Poříčí 25, Praha 1 — Nové Město",
    district: "Praha 1",
    description: "Součást mezinárodního řetězce veganských restaurací. Nabízí asijská jídla, polévky, saláty a dezerty za dostupné ceny.",
    tags: ["Asijská", "Mezinárodní", "Rozvoz", "S sebou"],
    dietaryOptions: ["bez-soji"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/loving-hut_4a7767b9.jpg",
    lat: 50.0921,
    lng: 14.4341,
    priceLevel: 1,
    hours: "Po–Pá 10:00–20:00, So 11:00–19:00",
    shoppingCenter: "Černá Labuť",
  },
  {
    id: "16",
    name: "Maitrea",
    slug: "maitrea",
    type: "vegetarian",
    rating: 4.8,
    reviewCount: 1240,
    isOpen: true,
    isPremium: true,
    address: "Týnská ulička 6, Praha 1 — Staré Město",
    district: "Praha 1",
    phone: "+420 221 711 631",
    website: "https://www.restaurace-maitrea.cz",
    description: "Dvě patra plná magických zákoutí a vegetariánské chutě inspirované srdcem. Interiér ve stylu Feng Shui s fontánami, krbem a sochou Buddhy. Dlouhodobě v Top 10 vegetariánských restaurací v Praze, držitel TripAdvisor Hall of Fame 2018.",
    tags: ["Vegetariánská", "Vegan-friendly", "Feng Shui", "Fine dining", "Rezervace"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/maitrea-vegetarianska-fine-dining-praha_0f9d6be3.webp",
    lat: 50.0878,
    lng: 14.4241,
    priceLevel: 3,
    hours: "Po–Ne 11:30–22:30",
  },
  {
    id: "17",
    name: "Lehká Hlava",
    slug: "lehka-hlava",
    type: "vegetarian",
    rating: 4.7,
    reviewCount: 980,
    isOpen: true,
    isPremium: true,
    address: "Boršov 280/2, Praha 1 — Staré Město",
    district: "Praha 1",
    phone: "+420 222 220 665",
    website: "https://www.lehkahlava.cz",
    description: "Jedna z nejstarších vegetariánských restaurací v Praze od roku 2005. Kreativní bezmasá kuchyně v kouzelném prostředí Starého Města, pár kroků od Karlova mostu. Každý pokoj zdoben jiným tématem — hvězdný strop, akvárium, modrý sál.",
    tags: ["Vegetariánská", "Vegan-friendly", "Tapas", "Džusy", "Sezónní menu"],
    dietaryOptions: ["bezlepkové", "raw"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/lehka-hlava-vegetarianska-restaurace-praha_38480d56.webp",
    lat: 50.0848,
    lng: 14.4138,
    priceLevel: 2,
    hours: "Po–Čt 11:30–22:30, Pá 11:30–23:00, So 12:00–23:00, Ne 12:00–22:30",
  },
  {
    id: "18",
    name: "Natureza",
    slug: "natureza",
    type: "vegetarian",
    rating: 4.6,
    reviewCount: 312,
    isOpen: true,
    isPremium: false,
    address: "Štefánikova 44, Praha 5 — Malá Strana",
    district: "Praha 5",
    phone: "+420 602 123 456",
    website: "https://www.natureza.cz",
    description: "Vegetariánská restaurace s kouzelnou zahradou v těsné blízkosti kostela sv. Vavřince. Denní menu (polévka + hlavní jídlo), vegetariánská, veganská i bezlepková jídla, raw dezerty. Vhodná i pro svatební hostiny.",
    tags: ["Vegetariánská", "Vegan-friendly", "Zahrada", "Bezlepkové", "Raw dezerty", "Catering"],
    dietaryOptions: ["bezlepkové", "raw"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/natureza-vegetarianska-restaurace-zahrada-praha_39ff3a7f.webp",
    lat: 50.0789,
    lng: 14.4031,
    priceLevel: 2,
    hours: "Po–Pá 11:00–21:00, So 12:00–21:00",
  },
  {
    id: "19",
    name: "Sandokan Vegan Bistro",
    slug: "sandokan-vegan-bistro",
    type: "vegan",
    rating: 4.5,
    reviewCount: 445,
    isOpen: true,
    isPremium: false,
    address: "Mánesova 1374/87, Praha 2 — Vinohrady",
    district: "Praha 2",
    phone: "+420 775 123 456",
    description: "Vinohradské veganské bistro s vysoce kvalitními čerstvými pokrmy včetně bezlepkové varianty. Samoobslužný bufet s výběrem zeleninových salátů a teplých jídel v libovolném množství.",
    tags: ["Veganská", "Bufet", "Bezlepkové", "Samoobslužný", "Vinohrady"],
    dietaryOptions: ["bezlepkové", "whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/sandokan-veganske-bistro-vinohrady_01ae168e.webp",
    lat: 50.0752,
    lng: 14.4412,
    priceLevel: 1,
    hours: "Po–Pá 11:00–20:00, So 12:00–18:00",
  },
  {
    id: "20",
    name: "Country Life",
    slug: "country-life",
    type: "vegan",
    rating: 4.4,
    reviewCount: 678,
    isOpen: true,
    isPremium: false,
    address: "Melantrichova 463/15, Praha 1 — Staré Město",
    district: "Praha 1",
    phone: "+420 224 213 366",
    website: "https://www.countrylife.cz",
    description: "Průkopník biopotravin v ČR od roku 1991. Teplá i studená veganská jídla, saláty, sendviče, burgery v příjemném prostředí. Prodej biopotravin, přírodní kosmetiky a produktů z vlastní ekofarmy. Preferuje bezobalový prodej.",
    tags: ["Veganská", "Bio", "Bufet", "Zdravá výživa", "Bezobalový", "S sebou"],
    dietaryOptions: ["bio", "whole-food", "bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/country-life_5ff4ebe4.png",
    lat: 50.0851,
    lng: 14.4201,
    priceLevel: 1,
    hours: "Po–Pá 9:00–20:00, So 10:00–18:00",
  },
  {
    id: "21",
    name: "Beas Dhaba — Vladislavova",
    slug: "beas-dhaba-vladislavova",
    type: "vegetarian",
    rating: 4.5,
    reviewCount: 780,
    isOpen: true,
    isPremium: false,
    address: "Vladislavova 24, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 773 380 371",
    website: "https://dhababeas.cz",
    description: "Jedna z nejoblíbenějších poboček řetězce Beas Dhaba. Samoobslužná vegetariánská a veganská restaurace s indickou, thajskou a vietnamskou kuchyní. Jídlo si naložíte a zaplatíte podle váhy — zdravé, chutné a cenově dostupné.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "S sebou", "Denní menu"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0795,
    lng: 14.4227,
    priceLevel: 1,
    hours: "Po–Pá 11:00–21:00, So–Ne 12:00–20:00",
  },
  {
    id: "29",
    name: "Beas Dhaba — Na Poříčí",
    slug: "beas-dhaba-na-porici",
    type: "vegetarian",
    rating: 4.4,
    reviewCount: 756,
    isOpen: true,
    isPremium: false,
    address: "Na Poříčí 26, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 725 963 536",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba v dvorku za divadlem Archa. Samoobslužný bufet s indickými a asijskými vegetariánskými pokrmy. Platíte podle váhy — ideální pro rychlý a levný oběd v centru Prahy.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "S sebou"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0901,
    lng: 14.4321,
    priceLevel: 1,
    hours: "Po–Pá 11:00–21:00, So–Ne 12:00–20:00",
  },
  {
    id: "30",
    name: "Beas Dhaba — Týnská",
    slug: "beas-dhaba-tynska",
    type: "vegetarian",
    rating: 4.3,
    reviewCount: 621,
    isOpen: true,
    isPremium: false,
    address: "Týnská 19, Praha 1 — Staré Město",
    district: "Praha 1",
    phone: "+420 608 035 727",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba schovaná v dvorku za Týnským chrámem na Staroměstském náměstí. Autentická indická vegetariánská kuchyně za skvělé ceny přímo v srdci Prahy.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "Staré Město"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0878,
    lng: 14.4230,
    priceLevel: 1,
    hours: "Po–Pá 11:00–20:00, So–Ne 12:00–20:00",
  },
  {
    id: "31",
    name: "Beas Dhaba — Purkyňova",
    slug: "beas-dhaba-purkynova",
    type: "vegetarian",
    rating: 4.3,
    reviewCount: 312,
    isOpen: true,
    isPremium: false,
    address: "Purkyňova 9, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 774 418 396",
    website: "https://dhababeas.cz",
    description: "Menší pobočka Beas Dhaba v klidné ulici nedaleko Václavského náměstí. Samoobslužný bufet s denně obměňovanou nabídkou indických a asijských jídel.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0818,
    lng: 14.4260,
    priceLevel: 1,
    hours: "Po–Pá 11:00–19:00, So–Ne zavřeno",
  },
  {
    id: "32",
    name: "Beas Dhaba — Palác Lucerna",
    slug: "beas-dhaba-palac-lucerna",
    type: "vegetarian",
    rating: 4.4,
    reviewCount: 534,
    isOpen: true,
    isPremium: false,
    address: "Štěpánská 61, Palác Lucerna, Praha 1",
    district: "Praha 1",
    phone: "+420 775 004 370",
    website: "https://dhababeas.cz",
    description: "Dvoupodlažní pobočka Beas Dhaba v ikonickém Paláci Lucerna. Přízemí pro rychlý oběd, první patro s plným menu až do večera. Oblíbené místo pro pracovní obědy i turisty.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "Lucerna"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0801,
    lng: 14.4255,
    priceLevel: 1,
    hours: "Po–Pá 11:00–21:00, So–Ne 12:00–20:00",
  },
  {
    id: "33",
    name: "Beas Dhaba — Slovanský dům",
    slug: "beas-dhaba-slovansky-dum",
    type: "vegetarian",
    rating: 4.5,
    reviewCount: 489,
    isOpen: true,
    isPremium: false,
    address: "Na Příkopě 22, Slovanský dům, Praha 1",
    district: "Praha 1",
    phone: "",
    website: "https://dhababeas.cz",
    description: "Pobočka v prestižním obchodním centru Slovanský dům na Na Příkopě. Vegetariánský bufet s indickou a asijskou kuchyní v moderním prostředí s příjemným posezením.",
    tags: ["Indická", "Vegetariánská", "Bufet", "OC", "Na Příkopě"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0849,
    lng: 14.4282,
    priceLevel: 1,
    hours: "Po–Pá 11:00–21:00, So–Ne 12:00–20:00",
    shoppingCenter: "Slovanský dům",
  },
  {
    id: "34",
    name: "Beas Dhaba — Bělehradská",
    slug: "beas-dhaba-belehradska",
    type: "vegetarian",
    rating: 4.4,
    reviewCount: 678,
    isOpen: true,
    isPremium: false,
    address: "Bělehradská 90, Praha 2 — Vinohrady",
    district: "Praha 2",
    phone: "+420 725 940 016",
    website: "https://dhababeas.cz",
    description: "Oblíbená pobočka Beas Dhaba ve Vinohradech. Samoobslužný bufet s bohatou nabídkou indických a thajských vegetariánských jídel. Klidné prostředí ideální pro oběd i večeři.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "Vinohrady"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0731,
    lng: 14.4310,
    priceLevel: 1,
    hours: "Po–Pá 11:00–21:00, So–Ne 12:00–20:00",
  },
  {
    id: "35",
    name: "Beas Dhaba — Hlavní nádraží",
    slug: "beas-dhaba-hlavni-nadrazi",
    type: "vegetarian",
    rating: 4.2,
    reviewCount: 445,
    isOpen: true,
    isPremium: false,
    address: "Wilsonova 300/8, Hlavní nádraží, Praha 2",
    district: "Praha 2",
    phone: "",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba v horní hale Hlavního nádraží. Otevřeno denně od rána do večera — ideální pro cestující hledající rychlé a zdravé vegetariánské jídlo.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "Nádraží"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0833,
    lng: 14.4348,
    priceLevel: 1,
    hours: "Po–Ne 7:00–22:00",
  },
  {
    id: "36",
    name: "Beas Dhaba — Karlovo náměstí",
    slug: "beas-dhaba-karlovo-namesti",
    type: "vegetarian",
    rating: 4.3,
    reviewCount: 367,
    isOpen: true,
    isPremium: false,
    address: "Karlovo náměstí 2097/10, Praha 2",
    district: "Praha 2",
    phone: "",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba na Karlově náměstí. Samoobslužný vegetariánský bufet s indickou kuchyní v blízkosti metra. Platíte podle váhy — rychlé a cenově dostupné.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0754,
    lng: 14.4184,
    priceLevel: 1,
    hours: "Po–Ne 11:00–20:00",
  },
  {
    id: "37",
    name: "Beas Dhaba — Na Pankráci",
    slug: "beas-dhaba-na-pankraci",
    type: "vegetarian",
    rating: 4.3,
    reviewCount: 289,
    isOpen: true,
    isPremium: false,
    address: "Na Pankráci 1683/127, Praha 4 — Nusle",
    district: "Praha 4",
    phone: "+420 601 592 216",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba v kancelářské čtvrti na Pankráci. Oblíbená volba pro pracovní obědy — rychlý vegetariánský bufet s indickými specialitami.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "Pankrác"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0530,
    lng: 14.4380,
    priceLevel: 1,
    hours: "Po–Pá 11:00–18:00, So–Ne zavřeno",
  },
  {
    id: "38",
    name: "Beas Dhaba — Vyskočilova",
    slug: "beas-dhaba-vyskocilova",
    type: "vegetarian",
    rating: 4.2,
    reviewCount: 198,
    isOpen: true,
    isPremium: false,
    address: "Vyskočilova 2, Praha 4 — Michle",
    district: "Praha 4",
    phone: "+420 774 738 983",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba v business parku na Vyskočilově. Samoobslužný vegetariánský bufet pro zaměstnance okolních kanceláří. Jídlo podle váhy za nejnižší ceny.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0445,
    lng: 14.4505,
    priceLevel: 1,
    hours: "Po–Pá 11:00–18:00, So–Ne zavřeno",
  },
  {
    id: "39",
    name: "Beas Dhaba Café — Nuselská",
    slug: "beas-dhaba-cafe-nuselska",
    type: "vegetarian",
    rating: 4.4,
    reviewCount: 234,
    isOpen: true,
    isPremium: false,
    address: "Nuselská 48, Praha 4 — Nusle",
    district: "Praha 4",
    phone: "+420 774 129 723",
    website: "https://dhababeas.cz",
    description: "Kavárna a snídaňové místo od Beas Dhaba v Nuslích. Otevřeno od rána — nabízí vegetariánské snídaně, kávu, zákusky a lehká jídla po celý den.",
    tags: ["Indická", "Vegetariánská", "Kavárna", "Snídaně", "Nusle"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0630,
    lng: 14.4340,
    priceLevel: 1,
    hours: "Po–Pá 8:00–20:00, So–Ne 9:00–20:00",
  },
  {
    id: "40",
    name: "Beas Dhaba — Nuselská",
    slug: "beas-dhaba-nuselska",
    type: "vegetarian",
    rating: 4.3,
    reviewCount: 345,
    isOpen: true,
    isPremium: false,
    address: "Nuselská 48 (ve dvoře), Praha 4 — Nusle",
    district: "Praha 4",
    phone: "+420 774 337 248",
    website: "https://dhababeas.cz",
    description: "Klasická pobočka Beas Dhaba v Nuslích, schovaná ve dvoře. Samoobslužný bufet s indickými a asijskými vegetariánskými pokrmy za skvělé ceny.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "Nusle"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0632,
    lng: 14.4342,
    priceLevel: 1,
    hours: "Po–Pá 11:00–20:00, So–Ne 12:00–19:00",
  },
  {
    id: "41",
    name: "Beas Dhaba — Viktora Huga",
    slug: "beas-dhaba-viktora-huga",
    type: "vegetarian",
    rating: 4.5,
    reviewCount: 267,
    isOpen: true,
    isPremium: false,
    address: "Viktora Huga 1, Praha 5 — Smíchov",
    district: "Praha 5",
    phone: "+420 773 042 911",
    website: "https://dhababeas.cz",
    description: "Nejlevnější pobočka Beas Dhaba v Praze! Pouze 29,90 Kč za 100 g. Samoobslužný bufet s indickou vegetariánskou kuchyní na Smíchově. Preferován odnos s sebou.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Nejlevnější", "Smíchov"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0700,
    lng: 14.4020,
    priceLevel: 1,
    hours: "Po–Pá 11:00–20:00, So–Ne zavřeno",
  },
  {
    id: "42",
    name: "Beas Dhaba — OC Nový Smíchov",
    slug: "beas-dhaba-oc-novy-smichov",
    type: "vegetarian",
    rating: 4.2,
    reviewCount: 412,
    isOpen: true,
    isPremium: false,
    address: "Plzeňská 8, OC Nový Smíchov, Praha 5",
    district: "Praha 5",
    phone: "+420 251 511 151",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba v obchodním centru Nový Smíchov. Vegetariánský bufet s indickou kuchyní ve food courtu. Otevřeno denně včetně víkendů.",
    tags: ["Indická", "Vegetariánská", "Bufet", "OC", "Nový Smíchov"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0720,
    lng: 14.4000,
    priceLevel: 1,
    hours: "Po–Ne 9:00–21:00",
    shoppingCenter: "OC Nový Smíchov",
  },
  {
    id: "43",
    name: "Beas Dhaba — Kyjevská",
    slug: "beas-dhaba-kyjevska",
    type: "vegetarian",
    rating: 4.3,
    reviewCount: 198,
    isOpen: true,
    isPremium: false,
    address: "Kyjevská 527/2, Praha 6 — Dejvice",
    district: "Praha 6",
    phone: "",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba v Dejvicích nedaleko metra Dejvická. Samoobslužný vegetariánský bufet oblíbený studenty a zaměstnanci okolních firem.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "Dejvice"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0995,
    lng: 14.3920,
    priceLevel: 1,
    hours: "Po–Pá 11:00–21:00, So–Ne 11:00–20:00",
  },
  {
    id: "44",
    name: "Beas Dhaba — Sokolovská",
    slug: "beas-dhaba-sokolovska",
    type: "vegetarian",
    rating: 4.1,
    reviewCount: 156,
    isOpen: true,
    isPremium: false,
    address: "Sokolovská 93, Praha 8",
    district: "Praha 8",
    phone: "+420 777 038 906",
    website: "https://dhababeas.cz",
    description: "Menší pobočka Beas Dhaba na Sokolovské. Otevřeno pouze v pracovní dny na oběd — ideální pro rychlý vegetariánský oběd v okolí Florenc.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0935,
    lng: 14.4510,
    priceLevel: 1,
    hours: "Po–Pá 11:00–15:00, So–Ne zavřeno",
  },
  {
    id: "45",
    name: "Beas Dhaba — Karlín",
    slug: "beas-dhaba-karlin",
    type: "vegetarian",
    rating: 4.4,
    reviewCount: 312,
    isOpen: true,
    isPremium: false,
    address: "Sokolovská 100/94, Praha 8 — Karlín",
    district: "Praha 8",
    phone: "+420 771 146 089",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba v trendy Karlíně. Vegetariánský bufet s indickou a asijskou kuchyní. O víkendech otevřeno s výhodnými slevami před zavírací dobou.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "Karlín"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0928,
    lng: 14.4530,
    priceLevel: 1,
    hours: "Po–Pá 11:00–19:00, So–Ne 11:00–18:00",
  },
  {
    id: "46",
    name: "Beas Dhaba — DOCK in Five",
    slug: "beas-dhaba-dock-in-five",
    type: "vegetarian",
    rating: 4.2,
    reviewCount: 134,
    isOpen: true,
    isPremium: false,
    address: "Boudníkova 13, DOCK in Five, Praha 8",
    district: "Praha 8",
    phone: "",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba v moderním kancelářském komplexu DOCK in Five v Libni. Vegetariánský bufet pro zaměstnance okolních firem.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "Libeň"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.1060,
    lng: 14.4590,
    priceLevel: 1,
    hours: "Po–Pá 11:00–19:00, So–Ne zavřeno",
  },
  {
    id: "47",
    name: "Beas Dhaba — OC Harfa",
    slug: "beas-dhaba-oc-harfa",
    type: "vegetarian",
    rating: 4.3,
    reviewCount: 278,
    isOpen: true,
    isPremium: false,
    address: "OC Harfa, Praha 9 — Vysočany",
    district: "Praha 9",
    phone: "",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba v obchodním centru Harfa. Vegetariánský bufet s indickou kuchyní ve food courtu. Otevřeno denně s happy hour slevou hodinu před zavírací dobou.",
    tags: ["Indická", "Vegetariánská", "Bufet", "OC", "Harfa"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.1035,
    lng: 14.4740,
    priceLevel: 1,
    hours: "Po–Ne 9:00–21:00",
    shoppingCenter: "OC Galerie Harfa",
  },
  {
    id: "48",
    name: "Beas Dhaba — OC Galerie Butovice",
    slug: "beas-dhaba-oc-galerie-butovice",
    type: "vegetarian",
    rating: 4.2,
    reviewCount: 189,
    isOpen: true,
    isPremium: false,
    address: "Radlická 520/117, OC Galerie Butovice, Praha 13",
    district: "Praha 13",
    phone: "",
    website: "https://dhababeas.cz",
    description: "Pobočka Beas Dhaba v obchodním centru Galerie Butovice na Praze 13. Vegetariánský bufet s indickou kuchyní. Otevřeno denně včetně víkendů.",
    tags: ["Indická", "Vegetariánská", "Bufet", "OC", "Butovice"],
    dietaryOptions: ["bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-sign_94735dc1.png",
    lat: 50.0510,
    lng: 14.3520,
    priceLevel: 1,
    hours: "Po–Ne 11:00–21:00",
    shoppingCenter: "OC Galerie Butovice",
  },
  {
    id: "49",
    name: "Spojka Karlín",
    slug: "spojka-karlin",
    type: "friendly",
    rating: 4.6,
    reviewCount: 534,
    isOpen: true,
    isPremium: false,
    address: "Lyčkovo náměstí 7, Praha 8 — Karlín",
    district: "Praha 8",
    phone: "+420 222 311 562",
    website: "https://www.spojkakarlin.cz",
    description: "První flexitariánská restaurace v ČR. A la carte menu s veganskými, vegetariánskými, bezlepkovými i masovými jídly, vše v bio kvalitě. Spojuje u jednoho stolu všechny bez předsudků.",
    tags: ["Flexitariánská", "Bio", "Vegan-friendly", "Bezlepkové", "Karlín"],
    dietaryOptions: ["bio", "bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spojka-karlin-flexitarianska-restaurace-praha_b80f1b8b.webp",
    lat: 50.0931,
    lng: 14.4512,
    priceLevel: 2,
    hours: "Po–Pá 11:30–22:00, So–Ne 12:00–22:00",
  },
  {
    id: "pp1",
    name: "Plavecká Polévka",
    slug: "plavecka-polevka",
    type: "friendly" as const,
    rating: 4.5,
    reviewCount: 312,
    isOpen: true,
    isPremium: false,
    address: "Plávecká 523/4, Praha 2 — Nové Město",
    district: "Praha 2",
    description: "Restaurace a bar s přátelskou atmosférou v blízkósti Pláveckého stadionu. Nabízejí širokou nabídku jídel včetně veganských a vegetariánských možností. Oblíbené místo pro obmědné menu i večeře.",
    tags: ["Vegan-friendly", "Vegetariánské možnosti", "Bar", "Oblíbené", "Praha 2"],
    dietaryOptions: ["whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/plavecka-polevka_66e369bb.jpg",
    lat: 50.0688,
    lng: 14.4225,
    priceLevel: 2,
    hours: "Po–Pá 11:00–22:00, So–Ne 12:00–22:00",
  },
  {
    id: "puzzlesalads",
    name: "Puzzlesalads",
    slug: "puzzlesalads",
    type: "friendly" as const,
    rating: 4.4,
    reviewCount: 410,
    isOpen: true,
    isPremium: false,
    address: "Revoluční 724/7, Praha 1 — Staré Město",
    district: "Praha 1",
    phone: "+420 722 922 791",
    website: "https://puzzlesalads.cz",
    description: "Zdravý fast-casual řetězec založený v roce 2014. Nabízí kvalitní, rychlé a zdravé jídlo z prvotníčních, sezónních a lokálních surovin. Saláty, bowly, těstoviny a více — včetně řady veganských možností. 12 poboček po celé Praze.",
    tags: ["Vegan-friendly", "Saláty", "Bowly", "Zdravé", "Rychlé občerstvení", "Praha 1"],
    dietaryOptions: ["whole-food", "bezlepkové"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/puzzlesalads_f57f6896.jpg",
    lat: 50.0899,
    lng: 14.4256,
    priceLevel: 2,
    hours: "Po–Pá 10:30–20:00, So–Ne 10:30–20:00",
  },
  {
    id: "23",
    name: "Veganland Express",
    slug: "veganland-express",
    type: "vegan",
    rating: 4.3,
    reviewCount: 267,
    isOpen: true,
    isPremium: false,
    address: "M. Horákové 398, Praha 7 — Letná",
    district: "Praha 7",
    description: "Veganské bistro na Letné se stálou nabídkou i samoobslužným bufetem. Nechybí ani výborné dezerty. Příjemná alternativa pro každodenní veganské stravování.",
    tags: ["Veganská", "Bufet", "Letná", "Dezerty", "S sebou"],
    dietaryOptions: ["whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganland-express-veganske-bistro-letna_c31564da.webp",
    lat: 50.1001,
    lng: 14.4201,
    priceLevel: 1,
    hours: "Po–Pá 10:00–21:00, So 11:00–20:00",
  },
  {
    id: "24",
    name: "Vegetka",
    slug: "vegetka",
    type: "vegan",
    rating: 4.2,
    reviewCount: 189,
    isOpen: true,
    isPremium: false,
    address: "Kafkova 605/16, Praha 6 — Dejvice",
    district: "Praha 6",
    description: "Veganská restaurace v těsné blízkosti metra A Dejvická. Samoobslužný pult s širokou nabídkou nejen asijské kuchyně. Rychlé a dostupné veganské stravování v Dejvicích.",
    tags: ["Veganská", "Asijská", "Samoobslužný", "Dejvice", "S sebou"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegetka-veganska-restaurace-dejvice_11b4e04b.webp",
    lat: 50.1021,
    lng: 14.3921,
    priceLevel: 1,
    hours: "Po–Pá 11:00–18:00, So 11:00–16:00",
  },
  {
    id: "25",
    name: "MyRaw Café",
    slug: "myraw-cafe",
    type: "vegan",
    rating: 4.4,
    reviewCount: 341,
    isOpen: true,
    isPremium: false,
    address: "Na Struze 1739/5, Praha 1 — Nové Město",
    district: "Praha 1",
    description: "Raw veganská kavárna v samém centru Prahy. Specialita na syrovou rostlinnou stravu — raw dezerty, smoothie bowls, čerstvé šťávy a raw hlavní jídla. Ideální pro příznivce raw food.",
    tags: ["Veganská", "Raw food", "Smoothie", "Dezerty", "Kavárna", "Centrum"],
    dietaryOptions: ["raw", "bezlepkové", "whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/myraw-cafe-raw-veganska-kavarna-praha_166573b7.webp",
    lat: 50.0821,
    lng: 14.4161,
    priceLevel: 2,
    hours: "Po–Ne 9:00–20:00",
  },
  {
    id: "26",
    name: "Chef & Co",
    slug: "chef-and-co",
    type: "vegan",
    rating: 4.3,
    reviewCount: 156,
    isOpen: false,
    isPremium: false,
    address: "Veleslavínova 93/10, Praha 1 — Staré Město",
    district: "Praha 1",
    description: "Restaurace s čistě rostlinnou nabídkou pokrmů v bio kvalitě v centru Prahy. Dočasně uzavřena. Kreativní veganská kuchyně s důrazem na bio suroviny.",
    tags: ["Veganská", "Bio", "Fine dining", "Centrum"],
    dietaryOptions: ["bio"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/chef-co-veganske-fine-dining-praha_98257ea9.webp",
    lat: 50.0871,
    lng: 14.4131,
    priceLevel: 3,
    hours: "Dočasně uzavřeno",
  },
  {
    id: "27",
    name: "Loving Bistro Pankrác",
    slug: "loving-bistro-pankrac",
    type: "vegan",
    rating: 4.1,
    reviewCount: 203,
    isOpen: true,
    isPremium: false,
    address: "Na Pankráci 86, Praha 4 — Nusle",
    district: "Praha 4",
    description: "Součást sítě veganských bistr Loving Hut. Veganský způsob stravování jako chutná, zdravá a vyvážená alternativa. Asijská jídla, polévky, saláty a dezerty za dostupné ceny.",
    tags: ["Veganská", "Asijská", "Bufet", "Pankrác", "Dostupné ceny"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/loving-hut_4a7767b9.jpg",
    lat: 50.0631,
    lng: 14.4321,
    priceLevel: 1,
    hours: "Po–Pá 10:30–20:30, So 11:00–20:30",
  },
  {
    id: "28",
    name: "Bistro pod Kavalírkou",
    slug: "bistro-pod-kavalirkou",
    type: "vegan",
    rating: 4.5,
    reviewCount: 87,
    isOpen: false,
    isPremium: false,
    address: "Pod Kavalírkou 471/38, Praha 5 — Košíře",
    district: "Praha 5",
    description: "Rostlinné bistro v Košířích s pestrou kuchyní, skvělými dezerty a různými nápoji. Útulné místo pro milovníky rostlinné stravy mimo centrum.",
    tags: ["Veganská", "Rostlinná strava", "Dezerty", "Košíře"],
    dietaryOptions: ["whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/bistro-pod-kavalirkou-rostlinne-bistro-kosire_676ba9f1.webp",
    lat: 50.0701,
    lng: 14.3901,
    priceLevel: 1,
    hours: "Dočasně uzavřeno",
  },
  // ── OC Branches ──────────────────────────────────────────
  {
    id: "50",
    name: "Loving Hut — OC Quadrio",
    slug: "loving-hut-oc-quadrio",
    type: "vegan",
    rating: 4.3,
    reviewCount: 185,
    isOpen: true,
    isPremium: false,
    address: "Spálená 22, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 770 631 690",
    website: "https://www.lovinghut.cz",
    description: "Veganské bistro v obchodním centru Quadrio. Samoobslužný bufet s asijskými jídly, polévkami, saláty a dezerty za dostupné ceny.",
    tags: ["Veganská", "Asijská", "Bufet", "OC Quadrio", "Dostupné ceny"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/loving-hut_4a7767b9.jpg",
    lat: 50.0803,
    lng: 14.4199,
    priceLevel: 1,
    hours: "Po–Pá 10:00–20:00, So–Ne 11:00–19:00",
    shoppingCenter: "OC Quadrio",
  },
  {
    id: "51",
    name: "Loving Hut — OC Nový Smíchov",
    slug: "loving-hut-oc-novy-smichov",
    type: "vegan",
    rating: 4.2,
    reviewCount: 210,
    isOpen: true,
    isPremium: false,
    address: "Plzeňská 8, Praha 5 — Smíchov",
    district: "Praha 5",
    phone: "+420 770 631 690",
    website: "https://www.lovinghut.cz",
    description: "Veganské bistro v OC Nový Smíchov. Samoobslužný bufet s asijskými jídly, polévkami, saláty a dezerty. Ideální zastávka při nakupování.",
    tags: ["Veganská", "Asijská", "Bufet", "OC Nový Smíchov", "Dostupné ceny"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/loving-hut_4a7767b9.jpg",
    lat: 50.0720,
    lng: 14.4030,
    priceLevel: 1,
    hours: "Po–So 10:00–21:00, Ne 10:00–20:00",
    shoppingCenter: "OC Nový Smíchov",
  },
  {
    id: "52",
    name: "Loving Hut — OC Zličín",
    slug: "loving-hut-oc-zlicin",
    type: "vegan",
    rating: 4.1,
    reviewCount: 142,
    isOpen: true,
    isPremium: false,
    address: "Řevnická 1, Praha 5 — Zličín",
    district: "Praha 5",
    phone: "+420 770 631 690",
    website: "https://www.lovinghut.cz",
    description: "Veganské bistro v OC Metropole Zličín. Samoobslužný bufet s asijskými jídly, polévkami, saláty a dezerty za dostupné ceny.",
    tags: ["Veganská", "Asijská", "Bufet", "OC Zličín", "Dostupné ceny"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/loving-hut_4a7767b9.jpg",
    lat: 50.0530,
    lng: 14.2890,
    priceLevel: 1,
    hours: "Po–So 10:00–21:00, Ne 10:00–20:00",
    shoppingCenter: "OC Metropole Zličín",
  },
  {
    id: "53",
    name: "Loving Hut — Jugoslávská",
    slug: "loving-hut-jugoslavska",
    type: "vegan",
    rating: 4.4,
    reviewCount: 196,
    isOpen: true,
    isPremium: false,
    address: "Jugoslávská 12, Praha 2 — Vinohrady",
    district: "Praha 2",
    phone: "+420 770 631 690",
    website: "https://www.lovinghut.cz",
    description: "Veganské bistro na Vinohradech. Samoobslužný bufet s asijskými jídly, polévkami, saláty a dezerty. Klidné prostředí v rezidenční čtvrti.",
    tags: ["Veganská", "Asijská", "Bufet", "Vinohrady", "Dostupné ceny"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/loving-hut_4a7767b9.jpg",
    lat: 50.0770,
    lng: 14.4370,
    priceLevel: 1,
    hours: "Po–Pá 10:00–20:00, So 11:00–19:00",
  },
  {
    id: "54",
    name: "Loving Hut — Budějovická",
    slug: "loving-hut-budejovicka",
    type: "vegan",
    rating: 4.2,
    reviewCount: 158,
    isOpen: true,
    isPremium: false,
    address: "Budějovická 13, Praha 4 — Krč",
    district: "Praha 4",
    phone: "+420 770 631 690",
    website: "https://www.lovinghut.cz",
    description: "Veganské bistro u metra Budějovická. Samoobslužný bufet s asijskými jídly, polévkami, saláty a dezerty za dostupné ceny.",
    tags: ["Veganská", "Asijská", "Bufet", "Budějovická", "Dostupné ceny"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/loving-hut_4a7767b9.jpg",
    lat: 50.0445,
    lng: 14.4490,
    priceLevel: 1,
    hours: "Po–Pá 10:00–20:00, So 11:00–19:00",
  },
  {
    id: "55",
    name: "Vegemama — OC Westfield Chodov",
    slug: "vegemama-oc-chodov",
    type: "vegan",
    rating: 4.0,
    reviewCount: 134,
    isOpen: true,
    isPremium: false,
    address: "Roztylská 2321/19, Praha 4 — Chodov",
    district: "Praha 4",
    description: "Vegetariánská a veganská samoobslužná restaurace v OC Westfield Chodov. Thajská a vietnamská kuchyně za dostupné ceny.",
    tags: ["Veganská", "Thajská", "Vietnamská", "Bufet", "OC Chodov"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganland-express-veganske-bistro-letna_c31564da.webp",
    lat: 50.0310,
    lng: 14.4910,
    priceLevel: 1,
    hours: "Po–Ne 10:00–21:00",
    shoppingCenter: "OC Westfield Chodov",
  },
  {
    id: "56",
    name: "Country Life — Melantrichova",
    slug: "country-life-melantrichova",
    type: "vegetarian",
    rating: 4.3,
    reviewCount: 312,
    isOpen: true,
    isPremium: false,
    address: "Melantrichova 15, Praha 1 — Staré Město",
    district: "Praha 1",
    phone: "+420 739 268 221",
    website: "https://www.countrylife.cz",
    description: "Prodejna biopotravin a vegetariánská restaurace v samém centru Prahy. Nabízí čerstvé saláty, polévky, teplá jídla a raw dezerty.",
    tags: ["Vegetariánská", "Bio", "Zdravá výživa", "Centrum", "S sebou"],
    dietaryOptions: ["bio", "raw"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/country-life_5ff4ebe4.png",
    lat: 50.0845,
    lng: 14.4195,
    priceLevel: 2,
    hours: "Po–Pá 8:00–18:00",
  },
  {
    id: "57",
    name: "Country Life — Jungmannova",
    slug: "country-life-jungmannova",
    type: "vegetarian",
    rating: 4.2,
    reviewCount: 189,
    isOpen: true,
    isPremium: false,
    address: "Jungmannova 1, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 224 213 366",
    website: "https://www.countrylife.cz",
    description: "Vegetariánská restaurace a prodejna biopotravin. Samoobslužný bufet s teplými jídly, saláty a dezerty v centru Prahy.",
    tags: ["Vegetariánská", "Bio", "Bufet", "Centrum", "Zdravá výživa"],
    dietaryOptions: ["bio", "raw"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/country-life_5ff4ebe4.png",
    lat: 50.0810,
    lng: 14.4230,
    priceLevel: 2,
    hours: "Po–Čt 10:30–18:00, Pá 10:30–15:00",
  },
  {
    id: "59",
    name: "Country Life — Spálená",
    slug: "country-life-spalena",
    type: "vegetarian" as const,
    rating: 4.2,
    reviewCount: 145,
    isOpen: true,
    isPremium: false,
    address: "Spálená 3, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 224 213 366",
    website: "https://www.countrylife.cz",
    description: "Další pobočka sítě Country Life v centru Prahy. Vegetariánská restaurace a prodejna biopotravin. Čerstvé saláty, polévky, teplná jídla a raw dezerty.",
    tags: ["Vegetariánská", "Bio", "Bufet", "Centrum", "Zdravá výživa"],
    dietaryOptions: ["bio", "raw"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/country-life_5ff4ebe4.png",
    lat: 50.0818,
    lng: 14.4175,
    priceLevel: 2,
    hours: "Po–Pá 9:00–18:00",
  },
  {
    id: "58",
    name: "Veganland — OC Westfield Chodov",
    slug: "veganland-oc-chodov",
    type: "vegan",
    rating: 4.1,
    reviewCount: 178,
    isOpen: true,
    isPremium: false,
    address: "Roztylská 2321/19, Praha 4 — Chodov",
    district: "Praha 4",
    description: "Veganské bistro v OC Westfield Chodov s bufetovou nabídkou. Asijská a mezinárodní kuchyně za dostupné ceny.",
    tags: ["Veganská", "Bufet", "OC Chodov", "Asijská", "Dostupné ceny"],
    dietaryOptions: ["whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganland-express-veganske-bistro-letna_c31564da.webp",
    lat: 50.0315,
    lng: 14.4905,
    priceLevel: 1,
    hours: "Po–Ne 10:00–21:00",
    shoppingCenter: "OC Westfield Chodov",
  },
  // ── DOBRÁ ČAJOVNA ──
  {
    id: "r29",
    name: "Dobrá čajovna Praha",
    slug: "dobra-cajovna-vaclavske-namesti",
    type: "vegetarian" as const,
    rating: 4.6,
    reviewCount: 214,
    isOpen: true,
    isPremium: false,
    address: "Václavské náměstí 14, 110 00 Praha 1",
    district: "Praha 1",
    phone: "+420 224 231 480",
    website: "https://www.dobracajovnapraha.cz",
    description: "Legendární čajovna otevřená od roku 1993 ve dvoře dolní části Václavského náměstí. Nabízí přes 200 druhů čajů z celého světa, vegetariánské a veganské pokrmy, dýmky a příjemnou atmosféru na měkkých polštářích. Jedno z nejkultovnějších míst v Praze.",
    tags: ["Čajovna", "Vegetariánské", "Veganské možnosti", "Čaj", "Dýmky", "Historické místo", "Praha 1"],
    dietaryOptions: ["whole-food"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/dobra-cajovna-praha-exterior_be6b556c.jpg",
    lat: 50.0808,
    lng: 14.4264,
    priceLevel: 1,
    hours: "Po–Pá 10:00–20:00, So–Ne 12:00–20:00",
  },
  // ── HAVELSKÁ KORUNA ──
  {
    id: "r30",
    name: "Havelská Koruna",
    slug: "havelska-koruna",
    type: "friendly" as const,
    rating: 4.2,
    reviewCount: 312,
    isOpen: true,
    isPremium: false,
    address: "Havelská 21, 110 00 Praha 1",
    district: "Praha 1",
    phone: "+420 224 239 413",
    website: "https://www.havelska-koruna.cz",
    description: "Tradiční česká jídelna v srdci Starého Města, fungující od roku 1971. Nabízí autentická česká jídla za dostupné ceny. Vegetariánské pokrmy zahrnují čočku na kyselo, koprovku s vejcem, smažený sýr a ovocné knedlíky. Oblíbené místo místních i turistů.",
    tags: ["Česká kuchyně", "Tradiční", "Vegetariánské možnosti", "Dostupné ceny", "Praha 1", "Jídelna"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/havelska-koruna-jidelna-stare-mesto_9a2e5c1d.jpg",
    lat: 50.0843,
    lng: 14.4218,
    priceLevel: 1,
    hours: "Po–Pá 9:00–20:00, So–Ne 10:00–18:00",
  },
  // ── FAST FOOD CHAINS ──
  {
    id: "ff1",
    name: "Burger King Praha",
    slug: "burger-king-praha",
    type: "fastfood" as const,
    rating: 3.8,
    reviewCount: 2140,
    isOpen: true,
    isPremium: false,
    address: "Náměstí Republiky 1, Praha 1",
    district: "Praha 1",
    phone: "+420 222 321 456",
    website: "https://www.burgerking.cz",
    description: "Burger King nabízejí několik vegetariánských a veganských možností. Rebel Whopper je rostlinný burger na bázi sojového proteinu. Plant-Based Nuggets jsou 100% veganské. Dostupné ve většině poboček v Praze.",
    tags: ["Fast Food", "Burger", "Rostlinné měso", "Vegan-friendly"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/burger-king_fe7fcf89.png",
    lat: 50.0875,
    lng: 14.4278,
    priceLevel: 1,
    hours: "Po–Ne 9:00–23:00",
    fastFoodItems: [
      { name: "Rebel Whopper", description: "Rostlinný burger s omeletou, salátem, rajské, cibulí a mayo. Sojový protein, připraven na stejném grilu jako masé burgery.", isVegan: false, price: "149 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/rebel-whopper-thumb_e76b188b.webp" },
      { name: "Plant-Based Nuggets (9 ks)", description: "100% veganské nugety z hrachého proteinu. Křupavé obalí, šťavnaté uvnitř. Vhodné pro vegany.", isVegan: true, price: "99 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/plant-based-nuggets-thumb_2ad90c11.webp" },
      { name: "Veggie King", description: "Vegetariánský burger s vejcem, sýrem, salátem a rajské. Klasický burger bez masa.", isVegan: false, price: "129 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veggie-king-thumb_0e9a0443.webp" },
      { name: "Onion Rings", description: "Cibulkové kroužky v křupavém těstíčku. Veganské přílohy.", isVegan: true, price: "59 Kč" },
      { name: "Apple Pie", description: "Jablečný závin v křupavém těstě. Veganský dezert.", isVegan: true, price: "39 Kč" },
    ],
  },

  {
    id: "ff3",
    name: "McDonald's Praha",
    slug: "mcdonalds-praha",
    type: "fastfood" as const,
    rating: 3.7,
    reviewCount: 3240,
    isOpen: true,
    isPremium: false,
    address: "Vodičkova 15, Praha 1",
    district: "Praha 1",
    phone: "+420 222 567 890",
    website: "https://www.mcdonalds.cz",
    description: "McDonald's nabízejí McVeggie burger a McPlant (100% veganský burger na bázi Beyond Meat). Vegetariánské možnosti zahrnují také hranolky, jablkové řízky a různé dezerty.",
    tags: ["Fast Food", "Burger", "Beyond Meat", "Vegan-friendly"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/mcdonalds_f9c46501.png",
    lat: 50.0823,
    lng: 14.4248,
    priceLevel: 1,
    hours: "Po–Ne 0:00–24:00",
    fastFoodItems: [
      { name: "McPlant", description: "100% veganský burger s Beyond Meat placčkou, veganským sýrem a veganským omáčkou. Certifikovaný vegan.", isVegan: true, price: "149 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/mcplant-thumb_7b4c92e8.webp" },
      { name: "McVeggie", description: "Vegetariánský burger s křupavou zeleninovou placčkou, salátem, rajské a mayo.", isVegan: false, price: "109 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/mcveggie-thumb_fb0318c9.webp" },
      { name: "Hranolky", description: "Klasické McDonald's hranolky. Veganské (smažené v rostlinném oleji).", isVegan: true, price: "49 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/mcdonalds-fries-thumb_f232d340.webp" },
      { name: "Apple Slices", description: "Jablečné řízky. Veganský zdravý dezert pro děti i dospělé.", isVegan: true, price: "29 Kč" },
      { name: "McFlurry Oreo", description: "Zmrzlinový dezert s Oreo sušenkami. Vegetariánský.", isVegan: false, price: "79 Kč" },
      { name: "Fruit Bag", description: "Ovocný sáček s hrozny a jablečnými řízky. Veganský.", isVegan: true, price: "39 Kč" },
    ],
  },
  {
    id: "ff4",
    name: "Subway Praha",
    slug: "subway-praha",
    type: "fastfood" as const,
    rating: 3.9,
    reviewCount: 1240,
    isOpen: true,
    isPremium: false,
    address: "Na Příkopě 14, Praha 1",
    district: "Praha 1",
    phone: "+420 222 678 901",
    website: "https://www.subway.com/cs-CZ",
    description: "Subway nabízejí širokou řadu vegetariánských a veganských sendvičů. Možnost výběru chleba, zeleniny a omáček. Veggie Delite je 100% veganský. Dostupné více poboček v Praze.",
    tags: ["Fast Food", "Sendvič", "Vegetariánské", "Vegan-friendly", "Zdravé"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/subway_5563f58e.png",
    lat: 50.0854,
    lng: 14.4265,
    priceLevel: 1,
    hours: "Po–Ne 8:00–22:00",
    fastFoodItems: [
      { name: "Veggie Delite", description: "Sendvič plněný čerstvou zeleninou bez masa. Možnost výběru veganského chleba a omáček. 100% veganský.", isVegan: true, price: "129 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/subway-veggie-delite-thumb_ff3cf959.webp" },
      { name: "Veggie Patty", description: "Sendvič s vegetariánskou placčkou ze zeleniny a luštěnin. Vegetariánský.", isVegan: false, price: "149 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/subway-veggie-patty-thumb_9f11fd7f.webp" },
      { name: "Beyond Meatball Marinara", description: "Sendvič s rostlinnými masovými kuličkami Beyond Meat v marinara omáčce. Veganský.", isVegan: true, price: "169 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beyond-meatball-marinara-thumb_57307927.webp" },
      { name: "Avocado", description: "Přidat avokádo do jakéhokoli sendviče. Veganské.", isVegan: true, price: "29 Kč" },
      { name: "Chips", description: "Křupavé brámbory. Většina příchutí je veganská.", isVegan: true, price: "39 Kč" },
    ],
  },
  {
    id: "ff5",
    name: "Pizza Hut Praha",
    slug: "pizza-hut-praha",
    type: "fastfood" as const,
    rating: 3.7,
    reviewCount: 890,
    isOpen: true,
    isPremium: false,
    address: "Wenceslas Square 56, Praha 1",
    district: "Praha 1",
    phone: "+420 222 789 012",
    website: "https://www.pizzahut.cz",
    description: "Pizza Hut nabízejí veganský sýr na všech pizzách. Vegetariánské pizzy zahrnují Margheritu, Veggie Supreme a Mushroom Lovers. Doručení po celé Praze.",
    tags: ["Fast Food", "Pizza", "Veganský sýr", "Vegetariánské", "Doručení"],
    dietaryOptions: [],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/pizza-hut_4d5d47fc.png",
    lat: 50.0796,
    lng: 14.4278,
    priceLevel: 2,
    hours: "Po–Ne 11:00–23:00",
    fastFoodItems: [
      { name: "Margherita (veganský sýr)", description: "Klasická Margherita s rajským protlakem a veganským sýrem. 100% veganská.", isVegan: true, price: "249 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/pizza-hut-margherita-thumb_ab7f99bc.webp" },
      { name: "Veggie Supreme", description: "Pizza s paprikou, houbami, cibulí, olivami a veganským sýrem. Veganská.", isVegan: true, price: "289 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/pizza-hut-veggie-supreme-thumb_2eaee646.webp" },
      { name: "Mushroom Lovers", description: "Pizza s třemi druhy hub a sýrem. Vegetariánská.", isVegan: false, price: "279 Kč", image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/pizza-hut-mushroom-lovers-thumb_65e6bbb0.webp" },
      { name: "Garlic Bread", description: "Cesnekový chleba. Veganský (bez masého másla).", isVegan: true, price: "79 Kč" },
      { name: "Tiramisu", description: "Klasický italský dezert. Vegetariánský.", isVegan: false, price: "89 Kč" },
    ],
  },

];

const RECIPE_PLACEHOLDER = "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/recipe-hero-kAEk42WS8auJkLKnU8C6NV.webp";

export const recipes: Recipe[] = [
  {
    id: "r1",
    title: "Veganská svíčková na smetaně",
    slug: "veganska-svickova",
    category: "Hlavní jídla",
    prepTime: 30,
    cookTime: 90,
    servings: 4,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-svickova-na-smetane-hlavni-jidlo_0fe2740b.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-svickova-na-smetane-hlavni-jidlo_0fe2740b.webp", alt: "Veganská svíčková na smetaně — hotové jídlo se seitanem, houskový knedlík a brusinkový dresink" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-svickova-kremova-omacka-detail_6962c182.webp", alt: "Detail krémové omáčky veganské svíčkové z kořenové zeleniny" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-svickova-suroviny-priprava_a3ca2a3e.webp", alt: "Suroviny na veganskou svíčkovou — kořenová zelenina, seitan, kešu ořechy a brusinky" },
    ],
    description: "Klasická česká svíčková v rostlinné verzi. Seitan místo hovězího, cashew smetana a tradiční omáčka z kořenové zeleniny.",
    tags: ["Česká kuchyně", "Seitan", "Tradiční"],
    isVegan: true,
  },
  {
    id: "r2",
    title: "Čočková polévka s uzenou paprikou",
    slug: "cocková-polevka-uzena-paprika",
    category: "Polévky",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cockova-polevka-uzena-paprika-miska_132d5585.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cockova-polevka-uzena-paprika-miska_132d5585.webp", alt: "Miska čočkové polévky s uzenou paprikou a chlebem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cockova-polevka-detail-textura-cocky_b71178dc.webp", alt: "Detail textury čočkové polévky s bylinkami a olivovým olejem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cockova-polevka-suroviny-na-stole_9683e532.webp", alt: "Suroviny na čočkovou polévku — červená čočka, uzená paprika, cibule a rajčata" },
    ],
    description: "Hustá a výživná čočková polévka s kouřovým aroma uzené papriky. Ideální na chladné dny.",
    tags: ["Polévka", "Čočka", "Rychlé"],
    isVegan: true,
  },
  {
    id: "r3",
    title: "Buddha bowl s pečenou zeleninou",
    slug: "buddha-bowl-pecena-zelenina",
    category: "Saláty a misky",
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/buddha-bowl-pecena-zelenina-barevna-miska_22ddaee1.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/buddha-bowl-pecena-zelenina-barevna-miska_22ddaee1.webp", alt: "Barevná buddha bowl miska s pečenou zeleninou, quinoou a avokádem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/buddha-bowl-detail-textury-zeleniny_624cb334.webp", alt: "Detail textur buddha bowlu — křupavá cizrna, krémové avokádo a pečená zelenina" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/buddha-bowl-priprava-ingredience_6887656e.webp", alt: "Příprava ingrediencí na buddha bowl — misky s quinoou, zeleninou a tahini" },
    ],
    description: "Barevná miska plná výživy — quinoa, pečená zelenina, avokádo, cizrna a tahini dresink.",
    tags: ["Bowl", "Quinoa", "Zdravé"],
    isVegan: true,
  },
  {
    id: "r4",
    title: "Veganský guláš s knedlíky",
    slug: "vegansky-gulas-knedliky",
    category: "Hlavní jídla",
    prepTime: 20,
    cookTime: 60,
    servings: 4,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-gulas-s-knedliky-cesky-talir_2cfd8972.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-gulas-s-knedliky-cesky-talir_2cfd8972.webp", alt: "Veganský guláš s houskovými knedlíky na tradičním českém talíři" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-gulas-detail-omacka-houby_3ec9d3d6.webp", alt: "Detail paprikové omáčky veganského guláše s houbami a seitanem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-gulas-suroviny-na-dreve_ab7d9793.webp", alt: "Suroviny na veganský guláš — houby, seitan, paprika, cibule a kmín" },
    ],
    description: "Tradiční český guláš bez masa — houby a seitan v bohaté paprikové omáčce s domácími houskových knedlíky.",
    tags: ["Česká kuchyně", "Guláš", "Tradiční"],
    isVegan: true,
  },
  {
    id: "r5",
    title: "Špenátové palačinky s tofu ricottou",
    slug: "spenatove-palacinkys-tofu-ricottou",
    category: "Snídaně",
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-palacinky-tofu-ricotta-talir_80a4da3d.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-palacinky-tofu-ricotta-talir_80a4da3d.webp", alt: "Špenátové palačinky plněné tofu ricottou na bílém talíři" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-palacinky-detail-naplne_782670bc.webp", alt: "Detail krémové tofu ricotta náplně uvnitř špenátové palačinky" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-palacinky-priprava-kuchyne_111cdf12.webp", alt: "Příprava špenátových palačinek v kuchyni — pánev, špenát a tofu ricotta" },
    ],
    description: "Zelené špenátové palačinky plněné krémovou tofu ricottou s citronem a čerstvými bylinkami.",
    tags: ["Snídaně", "Palačinky", "Špenát"],
    isVegan: true,
  },
  {
    id: "r6",
    title: "Houbové rizoto s parmezánem z kešu",
    slug: "houbove-rizoto-kešu-parmezan",
    category: "Hlavní jídla",
    prepTime: 10,
    cookTime: 35,
    servings: 3,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-kesu-parmezan-servir_1c17bb71.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-kesu-parmezan-servir_1c17bb71.webp", alt: "Houbové rizoto s veganským parmezánem z kešu ořechů a čerstvým tymiánem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-detail-houby-kremove_8426c27a.webp", alt: "Detail krémového houbového rizota s plátky lesních hub" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-suroviny-ingredience_7651caca.webp", alt: "Suroviny na houbové rizoto — arborio rýže, lesní houby, kešu ořechy a tymián" },
    ],
    description: "Krémové rizoto s lesními houbami a domácím veganským parmezánem z kešu ořechů.",
    tags: ["Italská", "Rizoto", "Houby"],
    isVegan: true,
  },
  // ── NEW SEO-OPTIMIZED RECIPES (r7–r24) ──────────────────────
  // Target keywords: palačinky (50k), bramborový salát (50k), brownies (50k),
  // rizoto (50k), bábovka (50k), pad thai (5k), pizza (5k), cheesecake (50k),
  // tortilla (5k), banana bread (5k), smoothie bowl (5k), špenátová polévka (5k),
  // květáková polévka (5k), cizrnové curry (5k), tofu recept (5k),
  // mexické fazole (5k), špenátové těstoviny (5k), hráškova polévka (5k)
  {
    id: "r7",
    title: "Veganské palačinky s ovocem",
    slug: "veganske-palacinky",
    category: "Snídaně",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganske-palacinky-recept-1_139cd8ea.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganske-palacinky-recept-1_139cd8ea.webp", alt: "Veganské palačinky s čerstvým ovocem a javorovým sirupem na talíři" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganske-palacinky-recept-2_767391fb.webp", alt: "Příprava těsta na veganské palačinky — míchání ingrediencí v misce" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganske-palacinky-recept-3_27d8ee75.webp", alt: "Smažení veganských palačinek na pánvi — zlatavá barva" },
    ],
    description: "Nadýchané veganské palačinky bez vajec a mléka. Podávané s čerstvým ovocem, javorovým sirupem a kokosovou šlehačkou. Ideální snídaně pro celou rodinu.",
    tags: ["Snídaně", "Palačinky", "Ovoce", "Rychlé"],
    isVegan: true,
  },
  {
    id: "r8",
    title: "Vegetariánský bramborový salát",
    slug: "vegetariansky-bramborovy-salat",
    category: "Saláty a misky",
    prepTime: 20,
    cookTime: 25,
    servings: 6,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegetariansky-bramborovy-salat-1_34c89298.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegetariansky-bramborovy-salat-1_34c89298.webp", alt: "Vegetariánský bramborový salát v míse — tradiční český recept bez masa" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegetariansky-bramborovy-salat-2_7aa3e080.webp", alt: "Detail bramborového salátu s nakládanými okurkami a majonézou" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegetariansky-bramborovy-salat-3_e71ef266.webp", alt: "Suroviny na vegetariánský bramborový salát — brambory, mrkev, hrášek, okurky" },
    ],
    description: "Tradiční český bramborový salát v bezmasé verzi. Krémový, s nakládanými okurkami, mrkví a hráškem. Ideální příloha ke svátečnímu stolu nebo na piknik.",
    tags: ["Salát", "Brambory", "Česká kuchyně", "Sváteční"],
    isVegan: false,
  },
  {
    id: "r9",
    title: "Veganské čokoládové brownies",
    slug: "veganske-brownies",
    category: "Dezerty",
    prepTime: 15,
    cookTime: 25,
    servings: 12,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganske-brownies-cokoladove-1_0992400b.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganske-brownies-cokoladove-1_0992400b.webp", alt: "Veganské čokoládové brownies nakrájené na čtverečky na prkénku" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganske-brownies-cokoladove-2_e1c0254a.webp", alt: "Detail veganského brownie — vlhká čokoládová textura s ořechy" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganske-brownies-cokoladove-3_40904c10.webp", alt: "Příprava těsta na veganské brownies — míchání kakaa a mouky" },
    ],
    description: "Neodolatelné čokoládové brownies bez vajec a másla. Vlhké, intenzivně čokoládové a s křupavou kůrkou. Nikdo nepozná, že jsou veganské!",
    tags: ["Dezert", "Čokoláda", "Brownies", "Pečení"],
    isVegan: true,
  },
  {
    id: "r10",
    title: "Houbové rizoto s veganským parmezánem",
    slug: "houbove-rizoto",
    category: "Hlavní jídla",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-s-parmazanem-1_31f82fa5.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-s-parmazanem-1_31f82fa5.webp", alt: "Krémové houbové rizoto s veganským parmezánem a čerstvým tymiánem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-s-parmazanem-2_bfb8e4b6.webp", alt: "Detail houbového rizota — arborio rýže s lesními houbami" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-s-parmazanem-3_2491cde6.webp", alt: "Suroviny na houbové rizoto — houby, arborio rýže, bílé víno, tymián" },
    ],
    description: "Luxusní krémové rizoto s lesními houbami a domácím veganským parmezánem z kešu. Italská klasika v rostlinné verzi, která chutná božsky.",
    tags: ["Italská", "Rizoto", "Houby", "Hlavní jídlo"],
    isVegan: true,
  },
  {
    id: "r11",
    title: "Veganská čokoládová bábovka",
    slug: "veganska-babovka",
    category: "Dezerty",
    prepTime: 15,
    cookTime: 50,
    servings: 10,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-babovka-cokoladova-1_9deb75a4.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-babovka-cokoladova-1_9deb75a4.webp", alt: "Veganská čokoládová bábovka s polevou na talíři" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-babovka-cokoladova-2_5b6d333f.webp", alt: "Řez veganskou bábovkou — vláčná čokoládová textura" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-babovka-cokoladova-3_15c7156d.webp", alt: "Příprava veganské bábovky — míchání těsta v míse" },
    ],
    description: "Vláčná čokoládová bábovka bez vajec a másla. Jednoduchý recept s bohatou čokoládovou chutí a lesklou polevou. Perfektní ke kávě.",
    tags: ["Dezert", "Bábovka", "Čokoláda", "Pečení"],
    isVegan: true,
  },
  {
    id: "r12",
    title: "Veganský pad thai s tofu",
    slug: "vegansky-pad-thai",
    category: "Hlavní jídla",
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-pad-thai-tofu-1_64db4e8f.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-pad-thai-tofu-1_64db4e8f.webp", alt: "Veganský pad thai s křupavým tofu a arašídy v misce" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-pad-thai-tofu-2_3fd91944.webp", alt: "Detail pad thai nudlí s tamarindovou omáčkou a limetkou" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-pad-thai-tofu-3_2aeab09b.webp", alt: "Příprava veganského pad thai — wok s nudlemi a zeleninou" },
    ],
    description: "Autentický thajský pad thai v rostlinné verzi s křupavým tofu, rýžovými nudlemi a domácí tamarindovou omáčkou. Rychlé a plné chutí.",
    tags: ["Asijská", "Thajská", "Tofu", "Nudle"],
    isVegan: true,
  },
  {
    id: "r13",
    title: "Domácí vegetariánská pizza",
    slug: "domaci-vegetarianska-pizza",
    category: "Hlavní jídla",
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/domaci-vegetarianska-pizza-1_8ac3d05a.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/domaci-vegetarianska-pizza-1_8ac3d05a.webp", alt: "Domácí vegetariánská pizza s čerstvou zeleninou a mozzarellou" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/domaci-vegetarianska-pizza-2_3071ba71.webp", alt: "Příprava těsta na domácí pizzu — hnětení a tvarování" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/domaci-vegetarianska-pizza-3_9f91afc6.webp", alt: "Vegetariánská pizza v peci — křupavý okraj a rozteklý sýr" },
    ],
    description: "Domácí pizza s křupavým těstem, rajčatovou omáčkou a bohatou zeleninovou náplní. Jednoduchý recept na dokonalou vegetariánskou pizzu.",
    tags: ["Italská", "Pizza", "Zelenina", "Domácí"],
    isVegan: false,
  },
  {
    id: "r14",
    title: "Veganský cheesecake s borůvkami",
    slug: "vegansky-cheesecake",
    category: "Dezerty",
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-cheesecake-boruvky-1_35845e39.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-cheesecake-boruvky-1_35845e39.webp", alt: "Veganský cheesecake s borůvkovou polevou na talíři" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-cheesecake-boruvky-2_4bbe6e4a.webp", alt: "Řez veganským cheesecakem — krémová kešu náplň a sušenková spodní vrstva" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-cheesecake-boruvky-3_1983f24c.webp", alt: "Příprava veganského cheesecaku — mixování kešu krému" },
    ],
    description: "Luxusní raw veganský cheesecake s krémovou kešu náplní a borůvkovou polevou. Bez pečení, bez cukru, plný chutí. Dokonalý dezert pro každou příležitost.",
    tags: ["Dezert", "Cheesecake", "Raw", "Borůvky"],
    isVegan: true,
  },
  {
    id: "r15",
    title: "Tortilla s grilovanou zeleninou",
    slug: "tortilla-grilovana-zelenina",
    category: "Hlavní jídla",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/tortilla-grilovana-zelenina-1_76225e56.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/tortilla-grilovana-zelenina-1_76225e56.webp", alt: "Tortilla wrap s grilovanou zeleninou, hummusem a čerstvými bylinkami" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/tortilla-grilovana-zelenina-2_78625efe.webp", alt: "Detail tortilly — grilovaná paprika, cuketa a avokádo" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/tortilla-grilovana-zelenina-3_49591b2b.webp", alt: "Příprava tortilly s grilovanou zeleninou — plnění a rolování" },
    ],
    description: "Křupavá tortilla plněná grilovanou zeleninou, domácím hummusem a čerstvými bylinkami. Rychlý a výživný oběd nebo svačina.",
    tags: ["Mexická", "Tortilla", "Grilování", "Rychlé"],
    isVegan: true,
  },
  {
    id: "r16",
    title: "Veganský banánový chléb",
    slug: "vegansky-bananovy-chleb",
    category: "Dezerty",
    prepTime: 10,
    cookTime: 55,
    servings: 8,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/bananovy-chleb-banana-bread-1_41c76e3c.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/bananovy-chleb-banana-bread-1_41c76e3c.webp", alt: "Veganský banánový chléb nakrájený na plátky na dřevěném prkénku" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/bananovy-chleb-banana-bread-2_aad010a5.webp", alt: "Detail banánového chleba — vláčná textura s kousky vlašských ořechů" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/bananovy-chleb-banana-bread-3_16bff2e6.webp", alt: "Suroviny na banánový chléb — zralé banány, mouka, ořechy a koření" },
    ],
    description: "Vláčný banánový chléb bez vajec a másla. Přirozeně sladký díky zralým banánům, s vlašskými ořechy a špetkou skořice. Ideální ke snídani nebo svačině.",
    tags: ["Dezert", "Banán", "Pečení", "Snídaně"],
    isVegan: true,
  },
  {
    id: "r17",
    title: "Smoothie bowl s ovocem a granolou",
    slug: "smoothie-bowl",
    category: "Snídaně",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/smoothie-bowl-ovoce-granola-1_96e77639.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/smoothie-bowl-ovoce-granola-1_96e77639.webp", alt: "Smoothie bowl s čerstvým ovocem, granolou a kokosem v misce" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/smoothie-bowl-ovoce-granola-2_e797df42.webp", alt: "Detail smoothie bowlu — borůvky, banán, chia semínka a med" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/smoothie-bowl-ovoce-granola-3_1cfa3c1d.webp", alt: "Příprava smoothie bowlu — mixování ovoce a zdobení toppingy" },
    ],
    description: "Barevná a výživná smoothie bowl s mixovaným ovocem, domácí granolou, kokosovými chipsy a chia semínky. Perfektní start do dne.",
    tags: ["Snídaně", "Smoothie", "Ovoce", "Zdravé"],
    isVegan: true,
  },
  {
    id: "r18",
    title: "Špenátová polévka s brambory",
    slug: "spenatova-polevka",
    category: "Polévky",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatova-polevka-brambory-1_114b941f.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatova-polevka-brambory-1_114b941f.webp", alt: "Krémová špenátová polévka s brambory v misce s kapkou smetany" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatova-polevka-brambory-2_38529bf4.webp", alt: "Detail špenátové polévky — sytě zelená barva s krutony" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatova-polevka-brambory-3_4fac738f.webp", alt: "Suroviny na špenátovou polévku — čerstvý špenát, brambory, česnek" },
    ],
    description: "Krémová špenátová polévka s brambory a česnekem. Sytá, výživná a plná železa. Klasika české kuchyně v lehké vegetariánské verzi.",
    tags: ["Polévka", "Špenát", "Brambory", "Česká kuchyně"],
    isVegan: false,
  },
  {
    id: "r19",
    title: "Květáková polévka se zázvorem",
    slug: "kvetakova-polevka",
    category: "Polévky",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/kvetakova-polevka-zazvor-1_ad157bb7.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/kvetakova-polevka-zazvor-1_ad157bb7.webp", alt: "Krémová květáková polévka se zázvorem a pečeným květákem navrch" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/kvetakova-polevka-zazvor-2_59388acd.webp", alt: "Detail květákové polévky — hedvábná textura s dýňovým olejem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/kvetakova-polevka-zazvor-3_5f488d82.webp", alt: "Suroviny na květákovou polévku — květák, zázvor, cibule, kokosové mléko" },
    ],
    description: "Hedvábně krémová květáková polévka s jemným zázvorem a kokosovým mlékem. Lehká, zahřívající a plná chutí. Ideální na chladné dny.",
    tags: ["Polévka", "Květák", "Zázvor", "Zdravé"],
    isVegan: true,
  },
  {
    id: "r20",
    title: "Cizrnové curry s kokosovým mlékem",
    slug: "cizrnove-curry",
    category: "Hlavní jídla",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cizrnove-curry-kokosove-mleko-1_e91d2994.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cizrnove-curry-kokosove-mleko-1_e91d2994.webp", alt: "Cizrnové curry s kokosovým mlékem a rýží v misce" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cizrnove-curry-kokosove-mleko-2_1d4be672.webp", alt: "Detail cizrnového curry — krémová omáčka s koriandrem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cizrnove-curry-kokosove-mleko-3_1c03b8da.webp", alt: "Suroviny na cizrnové curry — cizrna, kokosové mléko, rajčata, koření" },
    ],
    description: "Aromatické indické curry s cizrnou v krémové kokosové omáčce. Jednoduché, rychlé a neuvěřitelně chutné. Podávejte s basmati rýží a čerstvým koriandrem.",
    tags: ["Indická", "Curry", "Cizrna", "Kokos"],
    isVegan: true,
  },
  {
    id: "r21",
    title: "Tofu stir-fry se zeleninou",
    slug: "tofu-stir-fry",
    category: "Hlavní jídla",
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/tofu-stir-fry-zelenina-1_8ff0e75d.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/tofu-stir-fry-zelenina-1_8ff0e75d.webp", alt: "Tofu stir-fry s barevnou zeleninou ve woku" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/tofu-stir-fry-zelenina-2_c9639675.webp", alt: "Detail křupavého tofu se sezamem a sójovou omáčkou" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/tofu-stir-fry-zelenina-3_b3942374.webp", alt: "Příprava tofu stir-fry — smažení ve woku s paprikou a brokolicí" },
    ],
    description: "Rychlý a zdravý stir-fry s křupavým tofu a barevnou zeleninou v pikantní sójovo-zázvorové omáčce. Hotovo za 25 minut.",
    tags: ["Asijská", "Tofu", "Wok", "Rychlé"],
    isVegan: true,
  },
  {
    id: "r22",
    title: "Mexické fazole s rýží",
    slug: "mexicke-fazole-ryze",
    category: "Hlavní jídla",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/mexicke-fazole-ryze-1_a4b8d6fb.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/mexicke-fazole-ryze-1_a4b8d6fb.webp", alt: "Mexické fazole s rýží, avokádem a limetkou v misce" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/mexicke-fazole-ryze-2_808622ef.webp", alt: "Detail mexických fazolí — rajčatová omáčka s kukuřicí a paprikou" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/mexicke-fazole-ryze-3_e068aa50.webp", alt: "Suroviny na mexické fazole — černé fazole, rajčata, kukuřice, koření" },
    ],
    description: "Pikantní mexické fazole v rajčatové omáčce s kukuřicí, paprikou a koriandrem. Podávané s rýží a avokádem. Sytý a výživný bezmasý oběd.",
    tags: ["Mexická", "Fazole", "Rýže", "Pikantní"],
    isVegan: true,
  },
  {
    id: "r23",
    title: "Špenátové těstoviny s ricottou",
    slug: "spenatove-testoviny",
    category: "Hlavní jídla",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-testoviny-ricotta-1_14bb37c3.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-testoviny-ricotta-1_14bb37c3.webp", alt: "Špenátové těstoviny s ricottou a parmezánem na talíři" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-testoviny-ricotta-2_07559177.webp", alt: "Detail špenátových těstovin — krémová omáčka s čerstvým špenátem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-testoviny-ricotta-3_56647e06.webp", alt: "Příprava špenátových těstovin — míchání ricotty se špenátem v pánvi" },
    ],
    description: "Rychlé krémové těstoviny s čerstvým špenátem a ricottou. Jednoduchý italský recept, který zvládnete za 25 minut. Ideální na rychlý oběd.",
    tags: ["Italská", "Těstoviny", "Špenát", "Rychlé"],
    isVegan: false,
  },
  {
    id: "r24",
    title: "Hráškova polévka s mátou",
    slug: "hraskova-polevka",
    category: "Polévky",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/hraskova-polevka-mata-1_5fadcd06.webp",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/hraskova-polevka-mata-1_5fadcd06.webp", alt: "Krémová hráškova polévka s mátou a kapkou olivového oleje" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/hraskova-polevka-mata-2_c89f6376.webp", alt: "Detail hráškové polévky — sytě zelená barva s krutony" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/hraskova-polevka-mata-3_239744d7.webp", alt: "Suroviny na hráškovou polévku — hrášek, máta, cibule, česnek" },
    ],
    description: "Svěží a krémová hráškova polévka s čerstvou mátou. Sytě zelená, plná vitamínů a neuvěřitelně jednoduchá na přípravu. Skvělá teplá i studená.",
    tags: ["Polévka", "Hrášek", "Máta", "Zdravé"],
    isVegan: true,
  },
];

export const districts = [
  "Všechny čtvrti",
  "Praha 1",
  "Praha 2",
  "Praha 3",
  "Praha 4",
  "Praha 5",
  "Praha 6",
  "Praha 7",
  "Praha 8",
  "Praha 9",
  "Praha 10",
  "Praha 13",
];

export const cuisineTags = [
  "Česká kuchyně",
  "Asijská",
  "Italská",
  "Indická",
  "Vietnamská",
  "Mezinárodní",
  "Organická",
  "Raw",
  "Snídaně",
  "Pekárna",
];

export const dietaryOptionsConfig: { value: DietaryOption; label: string; icon: string }[] = [
  { value: "bezlepkové", label: "Bezlepkové", icon: "🌾" },
  { value: "raw", label: "Raw food", icon: "🥦" },
  { value: "bio", label: "Bio / Organic", icon: "🌱" },
  { value: "whole-food", label: "Whole food", icon: "🥜" },
  { value: "bez-soji", label: "Bez sóji", icon: "🚫" },
  { value: "bez-oriskove", label: "Bez ořechů", icon: "🥜" },
  { value: "ayurvédské", label: "Ayurvédské", icon: "🧘" },
  { value: "makrobiotické", label: "Makrobiotické", icon: "☘️" },
  { value: "low-carb", label: "Low carb", icon: "📉" },
  { value: "high-protein", label: "High protein", icon: "💪" },
];

export const getTypeLabel = (type: RestaurantType): string => {
  switch (type) {
    case "vegan": return "Veganská restaurace";
    case "vegetarian": return "Vegetariánská restaurace";
    case "friendly": return "Vegan-friendly";
    case "fastfood": return "Fast Food";
    default: return "Restaurace";
  }
};

export const getTypeColor = (type: RestaurantType): string => {
  switch (type) {
    case "vegan": return "bg-emerald-700 text-white";
    case "vegetarian": return "bg-emerald-500 text-white";
    case "friendly": return "bg-amber-400 text-amber-900";
    case "fastfood": return "bg-orange-500 text-white";
    default: return "bg-gray-400 text-white";
  }
};

export const renderStars = (rating: number): { filled: number; half: boolean; empty: number } => {
  const filled = Math.floor(rating);
  const half = rating % 1 >= 0.5;
  const empty = 5 - filled - (half ? 1 : 0);
  return { filled, half, empty };
};
