// ============================================================
// BEZMASAJIDLA.CZ — Restaurant & Recipe Data
// "Zelená Metropole" design system
// ============================================================

export type RestaurantType = "vegan" | "vegetarian" | "friendly";

export interface Restaurant {
  id: string;
  name: string;
  slug: string;
  type: RestaurantType;
  rating: number;
  reviewCount: number;
  isOpen: boolean;
  isPremium: boolean;
  address: string;
  district: string;
  phone?: string;
  website?: string;
  description: string;
  tags: string[];
  image: string;
  lat: number;
  lng: number;
  priceLevel: 1 | 2 | 3;
  hours?: string;
}

export interface RecipeImage {
  url: string;
  alt: string;
}

export interface Recipe {
  id: string;
  title: string;
  slug: string;
  category: string;
  prepTime: number;
  cookTime: number;
  servings: number;
  difficulty: "snadný" | "střední" | "náročný";
  image: string;
  images: RecipeImage[];
  description: string;
  tags: string[];
  isVegan: boolean;
}

const RESTAURANT_PLACEHOLDER = "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/restaurant-placeholder-NfsuHQoJhFmyxCXwn7EygE.webp";

export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "Shromaždiště",
    slug: "shromazdistepraha",
    type: "vegan",
    rating: 5.0,
    reviewCount: 223,
    isOpen: false,
    isPremium: true,
    address: "Krásova 13, Praha 3 — Žižkov",
    district: "Praha 3",
    phone: "+420 776 148 259",
    description: "Veganský gastropub specializovaný na veganizaci tradičních českých jídel. Také nabízí výběr naložených/špinavých hranolek. Nachází se v tradiční a rustikální české hospodě v Žižkově.",
    tags: ["Česká kuchyně", "Americká", "Fast food", "Pivo/Víno", "Evropská"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/shromazdiste-vegansky-gastropub-praha_d8c02b20.png",
    lat: 50.0820,
    lng: 14.4501,
    priceLevel: 2,
    hours: "Po–Pá 11:00–22:00, So–Ne 12:00–22:00",
  },
  {
    id: "2",
    name: "Dosa Dosa",
    slug: "dosa-dosa",
    type: "vegan",
    rating: 5.0,
    reviewCount: 251,
    isOpen: false,
    isPremium: true,
    address: "Újezd 43, Praha 1 — Malá Strana",
    district: "Praha 1",
    phone: "+420 725 511 536",
    description: "Veganská jídelna/kavárna servírující dosy, indická a asijská jídla a dezerty. Nabízí také českou kuchyni jako součást denního menu.",
    tags: ["Indická", "Organická", "Thajská", "Asijská", "Pekárna", "Snídaně", "Bezlepková"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/dosa-dosa-veganska-indicka-restaurace-praha_c42f79c4.jpg",
    lat: 50.0833,
    lng: 14.4033,
    priceLevel: 2,
    hours: "Po–Ne 10:00–21:00",
  },
  {
    id: "3",
    name: "Share Sweet and Espresso Bar",
    slug: "share-sweet-espresso",
    type: "vegan",
    rating: 5.0,
    reviewCount: 334,
    isOpen: false,
    isPremium: false,
    address: "Revoluční 18, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 771 151 113",
    description: "Veganský sladký a espresso bar provozovaný restaurací Palo Verde. Servíruje kávu, svačiny, obědy a dorty. Nabízí catering, narozeninové a svatební dorty.",
    tags: ["Pekárna", "Catering", "Snídaně", "Rozvoz", "S sebou"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/share-sweet-espresso-bar-veganska-kavarna-praha_49623671.jpg",
    lat: 50.0897,
    lng: 14.4282,
    priceLevel: 1,
    hours: "Po–Pá 8:00–18:00, So 9:00–17:00",
  },
  {
    id: "4",
    name: "Chutnej",
    slug: "chutnej",
    type: "vegan",
    rating: 5.0,
    reviewCount: 335,
    isOpen: true,
    isPremium: true,
    address: "Letohradská 50, Praha 7 — Holešovice",
    district: "Praha 7",
    phone: "+420 222 250 724",
    description: "Rostlinná restaurace a kavárna poblíž Letenské pláně. Nabízí denní brunch, oběd a sdílené večerní menu. Má také dezerty včetně pečiva ze sesterského podniku Krafin.",
    tags: ["Italská", "Středomořská", "Pivo/Víno", "Snídaně", "S sebou"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/chutnej-rostlinna-restaurace-praha_b868fc30.jpg",
    lat: 50.1012,
    lng: 14.4201,
    priceLevel: 2,
    hours: "Po–Pá 9:00–22:00, So–Ne 10:00–22:00",
  },
  {
    id: "5",
    name: "Eaternia",
    slug: "eaternia",
    type: "vegan",
    rating: 5.0,
    reviewCount: 150,
    isOpen: false,
    isPremium: false,
    address: "Nádražní 349/3, Praha 5 — Smíchov",
    district: "Praha 5",
    description: "Veganský podnik v budově bývalé sladovny mezi dvěma železničními mosty. Sezónní pokrmy z místních surovin. Burgery, hot dogy, tradiční česká kuchyně a saláty.",
    tags: ["Americká", "Mezinárodní", "Pivo/Víno", "Catering", "Rozvoz"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/eaternia-veganska-restaurace-praha_e9d6cb9b.jpg",
    lat: 50.0701,
    lng: 14.4052,
    priceLevel: 2,
    hours: "Út–Ne 12:00–21:00",
  },
  {
    id: "6",
    name: "Palo Verde",
    slug: "palo-verde",
    type: "vegan",
    rating: 4.5,
    reviewCount: 676,
    isOpen: true,
    isPremium: true,
    address: "Žitná 45, Praha 2 — Nové Město",
    district: "Praha 2",
    phone: "+420 775 285 430",
    description: "Rostlinný bistro s organickými víny a kávovými nápoji, denním výběrem pečiva a croissantů a slanými pokrmy jako čerstvě vyrobené těstoviny, houbové ravioli, Beyond burger, fusion misky a španské tapas.",
    tags: ["Organická", "Pivo/Víno", "Pekárna", "Španělská", "Česká", "Fusion"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/palo-verde-rostlinne-bistro-praha_e364e468.jpg",
    lat: 50.0762,
    lng: 14.4261,
    priceLevel: 2,
    hours: "Po–Pá 8:00–22:00, So–Ne 9:00–22:00",
  },
  {
    id: "7",
    name: "Střecha",
    slug: "strecha",
    type: "vegan",
    rating: 4.5,
    reviewCount: 797,
    isOpen: true,
    isPremium: false,
    address: "Křemencova 7, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 737 048 487",
    description: "Sociální podnik veganská restaurace zaměstnávající lidi bez domova a lidi po propuštění z vězení. Nabízí obědová menu, českou veganskou kuchyni, fair-trade kávu a alkoholické nápoje.",
    tags: ["Mezinárodní", "Pivo/Víno", "Catering", "Česká"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/strecha-veganska-restaurace-praha_e6ed5ed3.jpg",
    lat: 50.0788,
    lng: 14.4181,
    priceLevel: 1,
    hours: "Po–Pá 11:00–21:00",
  },
  {
    id: "8",
    name: "Koko Organic",
    slug: "koko-organic",
    type: "vegetarian",
    rating: 5.0,
    reviewCount: 58,
    isOpen: false,
    isPremium: false,
    address: "Biskupská 1753/5, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 777 583 999",
    description: "Vegetariánský vietnamský podnik. Servíruje rýži, nudle a pad thai pokrmy. Téměř všechna jídla jsou veganská.",
    tags: ["Asijská", "Vietnamská", "Organická"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/koko-organic-vegetarianska-vietnamska-praha_332be252.jpg",
    lat: 50.0901,
    lng: 14.4361,
    priceLevel: 1,
    hours: "Po–So 11:00–20:00",
  },
  {
    id: "9",
    name: "Linh — Not Just A Restaurant",
    slug: "linh-restaurant",
    type: "vegan",
    rating: 4.5,
    reviewCount: 454,
    isOpen: true,
    isPremium: true,
    address: "Mánesova 7, Praha 2 — Vinohrady",
    district: "Praha 2",
    phone: "+420 608 045 711",
    description: "Veganská vietnamská restaurace s pohádkovým interiérem. Nabízí rostlinná teplá jídla spolu s domácími dezerty, raw dorty, čerstvými džusy, smoothie a horkými nápoji. Pho, burgery, banh mi a pad thai.",
    tags: ["Mezinárodní", "Pivo/Víno", "Asijská", "Vietnamská", "Bezlepková"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/linh-veganska-vietnamska-restaurace-praha_59241983.jpg",
    lat: 50.0762,
    lng: 14.4401,
    priceLevel: 2,
    hours: "Po–Ne 11:00–22:00",
  },
  {
    id: "10",
    name: "Vegan's Prague",
    slug: "vegans-prague",
    type: "vegan",
    rating: 4.5,
    reviewCount: 884,
    isOpen: false,
    isPremium: false,
    address: "Nerudova 36, Praha 1 — Malá Strana",
    district: "Praha 1",
    phone: "+420 735 171 313",
    description: "Veganská restaurace v budově z 16. století poblíž Pražského hradu s terasou a výhledem, zal. 2016. Domácí česká a mezinárodní kuchyně. Guláš, raw čokoládový dort, bruschetta, sójové latte, cuketové lasagne.",
    tags: ["Mezinárodní", "Organická", "Raw", "Juice bar", "Česká"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegans-prague-veganska-restaurace-prazsky-hrad_0b442ee7.jpg",
    lat: 50.0882,
    lng: 14.4001,
    priceLevel: 2,
    hours: "Po–Ne 11:00–21:00",
  },
  {
    id: "11",
    name: "Belzepub",
    slug: "belzepub",
    type: "vegan",
    rating: 4.5,
    reviewCount: 185,
    isOpen: true,
    isPremium: false,
    address: "Záhřebská 6, Praha 2 — Vinohrady",
    district: "Praha 2",
    description: "Veganský bar a restaurace s výběrem piv, koktejlů a jídel. Přátelská atmosféra v srdci Vinohrad.",
    tags: ["Pivo/Víno", "Česká", "Mezinárodní"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/belzepub-vegansky-bar-praha_eb4792f1.jpg",
    lat: 50.0741,
    lng: 14.4421,
    priceLevel: 2,
    hours: "Po–Ne 16:00–01:00",
  },
  {
    id: "12",
    name: "Herbivore",
    slug: "herbivore",
    type: "vegan",
    rating: 4.5,
    reviewCount: 134,
    isOpen: false,
    isPremium: false,
    address: "Mánesova 59, Praha 2 — Vinohrady",
    district: "Praha 2",
    description: "Útulná veganská kavárna a bistro na Vinohradech. Domácí pečivo, snídaně, obědy a dezerty.",
    tags: ["Snídaně", "Pekárna", "Káva"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/herbivore-veganske-bistro-vinohrady_d6bfed1f.jpg",
    lat: 50.0752,
    lng: 14.4441,
    priceLevel: 1,
    hours: "Po–Pá 8:00–18:00, So–Ne 9:00–17:00",
  },
  {
    id: "13",
    name: "Pastva",
    slug: "pastva",
    type: "vegetarian",
    rating: 4.5,
    reviewCount: 179,
    isOpen: true,
    isPremium: false,
    address: "Mánesova 87, Praha 2 — Vinohrady",
    district: "Praha 2",
    description: "Vegetariánská restaurace s důrazem na lokální a sezónní suroviny. Kreativní pokrmy inspirované českou i mezinárodní kuchyní.",
    tags: ["Česká", "Mezinárodní", "Organická", "Sezónní"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/pastva-vegetarianska-restaurace-praha_758414c7.jpg",
    lat: 50.0731,
    lng: 14.4461,
    priceLevel: 2,
    hours: "Út–Ne 12:00–22:00",
  },
  {
    id: "14",
    name: "Onigirazu",
    slug: "onigirazu",
    type: "friendly",
    rating: 4.5,
    reviewCount: 69,
    isOpen: false,
    isPremium: false,
    address: "Korunní 18, Praha 2 — Vinohrady",
    district: "Praha 2",
    description: "Japonský podnik specializovaný na onigirazu — japonské sendviče z rýže. Mnoho veganských možností.",
    tags: ["Japonská", "Asijská", "S sebou"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/onigirazu-japonske-jidlo-praha_daca78f3.jpg",
    lat: 50.0771,
    lng: 14.4381,
    priceLevel: 1,
    hours: "Po–So 11:00–19:00",
  },
  {
    id: "15",
    name: "Loving Hut — Na Poříčí",
    slug: "loving-hut-na-porici",
    type: "vegan",
    rating: 4.5,
    reviewCount: 238,
    isOpen: false,
    isPremium: false,
    address: "Na Poříčí 25, Praha 1 — Nové Město",
    district: "Praha 1",
    description: "Součást mezinárodního řetězce veganských restaurací. Nabízí asijská jídla, polévky, saláty a dezerty za dostupné ceny.",
    tags: ["Asijská", "Mezinárodní", "Rozvoz", "S sebou"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/loving-hut-na-porici-veganska-restaurace_a795d30a.jpg",
    lat: 50.0921,
    lng: 14.4341,
    priceLevel: 1,
    hours: "Po–Pá 10:00–20:00, So 11:00–19:00",
  },
  {
    id: "16",
    name: "Maitrea",
    slug: "maitrea",
    type: "vegetarian",
    rating: 4.8,
    reviewCount: 1240,
    isOpen: true,
    isPremium: true,
    address: "Týnská ulička 6, Praha 1 — Staré Město",
    district: "Praha 1",
    phone: "+420 221 711 631",
    website: "https://www.restaurace-maitrea.cz",
    description: "Dvě patra plná magických zákoutí a vegetariánské chutě inspirované srdcem. Interiér ve stylu Feng Shui s fontánami, krbem a sochou Buddhy. Dlouhodobě v Top 10 vegetariánských restaurací v Praze, držitel TripAdvisor Hall of Fame 2018.",
    tags: ["Vegetariánská", "Vegan-friendly", "Feng Shui", "Fine dining", "Rezervace"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/maitrea-vegetarianska-fine-dining-praha_4b7a231a.jpg",
    lat: 50.0878,
    lng: 14.4241,
    priceLevel: 3,
    hours: "Po–Ne 11:30–22:30",
  },
  {
    id: "17",
    name: "Lehká Hlava",
    slug: "lehka-hlava",
    type: "vegetarian",
    rating: 4.7,
    reviewCount: 980,
    isOpen: true,
    isPremium: true,
    address: "Boršov 280/2, Praha 1 — Staré Město",
    district: "Praha 1",
    phone: "+420 222 220 665",
    website: "https://www.lehkahlava.cz",
    description: "Jedna z nejstarších vegetariánských restaurací v Praze od roku 2005. Kreativní bezmasá kuchyně v kouzelném prostředí Starého Města, pár kroků od Karlova mostu. Každý pokoj zdoben jiným tématem — hvězdný strop, akvárium, modrý sál.",
    tags: ["Vegetariánská", "Vegan-friendly", "Tapas", "Džusy", "Sezónní menu"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/lehka-hlava-vegetarianska-restaurace-praha_caeb1735.jpg",
    lat: 50.0848,
    lng: 14.4138,
    priceLevel: 2,
    hours: "Po–Čt 11:30–22:30, Pá 11:30–23:00, So 12:00–23:00, Ne 12:00–22:30",
  },
  {
    id: "18",
    name: "Natureza",
    slug: "natureza",
    type: "vegetarian",
    rating: 4.6,
    reviewCount: 312,
    isOpen: true,
    isPremium: false,
    address: "Štefánikova 44, Praha 5 — Malá Strana",
    district: "Praha 5",
    phone: "+420 602 123 456",
    website: "https://www.natureza.cz",
    description: "Vegetariánská restaurace s kouzelnou zahradou v těsné blízkosti kostela sv. Vavřince. Denní menu (polévka + hlavní jídlo), vegetariánská, veganská i bezlepková jídla, raw dezerty. Vhodná i pro svatební hostiny.",
    tags: ["Vegetariánská", "Vegan-friendly", "Zahrada", "Bezlepkové", "Raw dezerty", "Catering"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/natureza-vegetarianska-restaurace-zahrada-praha_b7174c8e.jpg",
    lat: 50.0789,
    lng: 14.4031,
    priceLevel: 2,
    hours: "Po–Pá 11:00–21:00, So 12:00–21:00",
  },
  {
    id: "19",
    name: "Sandokan Vegan Bistro",
    slug: "sandokan-vegan-bistro",
    type: "vegan",
    rating: 4.5,
    reviewCount: 445,
    isOpen: true,
    isPremium: false,
    address: "Mánesova 1374/87, Praha 2 — Vinohrady",
    district: "Praha 2",
    phone: "+420 775 123 456",
    description: "Vinohradské veganské bistro s vysoce kvalitními čerstvými pokrmy včetně bezlepkové varianty. Samoobslužný bufet s výběrem zeleninových salátů a teplých jídel v libovolném množství.",
    tags: ["Veganská", "Bufet", "Bezlepkové", "Samoobslužný", "Vinohrady"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/sandokan-veganske-bistro-vinohrady_afb8b906.png",
    lat: 50.0752,
    lng: 14.4412,
    priceLevel: 1,
    hours: "Po–Pá 11:00–20:00, So 12:00–18:00",
  },
  {
    id: "20",
    name: "Country Life",
    slug: "country-life",
    type: "vegan",
    rating: 4.4,
    reviewCount: 678,
    isOpen: true,
    isPremium: false,
    address: "Melantrichova 463/15, Praha 1 — Staré Město",
    district: "Praha 1",
    phone: "+420 224 213 366",
    website: "https://www.countrylife.cz",
    description: "Průkopník biopotravin v ČR od roku 1991. Teplá i studená veganská jídla, saláty, sendviče, burgery v příjemném prostředí. Prodej biopotravin, přírodní kosmetiky a produktů z vlastní ekofarmy. Preferuje bezobalový prodej.",
    tags: ["Veganská", "Bio", "Bufet", "Zdravá výživa", "Bezobalový", "S sebou"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/country-life-vegansky-bufet-praha_d58e3685.jpg",
    lat: 50.0851,
    lng: 14.4201,
    priceLevel: 1,
    hours: "Po–Pá 9:00–20:00, So 10:00–18:00",
  },
  {
    id: "21",
    name: "Beas Dhaba",
    slug: "beas-dhaba",
    type: "vegetarian",
    rating: 4.5,
    reviewCount: 892,
    isOpen: true,
    isPremium: false,
    address: "Na Poříčí 32, Praha 1 — Nové Město",
    district: "Praha 1",
    phone: "+420 608 035 727",
    website: "https://www.beas-dhaba.cz",
    description: "Rušná indická jídelna na několika místech v Praze. Ideální pro rychlé a levné jídlo. Z denní nabídky si naložíte tolik, na kolik máte chuť, a u pokladny vám jídlo zváží. Zdravá a chutná alternativa, většina jídel není příliš ostrá.",
    tags: ["Indická", "Vegetariánská", "Bufet", "Levné", "S sebou", "Denní menu"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/beas-dhaba-indicka-vegetarianska-jidelna-praha_983284c8.jpg",
    lat: 50.0901,
    lng: 14.4321,
    priceLevel: 1,
    hours: "Po–Pá 11:00–20:00, So–Ne 12:00–19:00",
  },
  {
    id: "22",
    name: "Spojka Karlín",
    slug: "spojka-karlin",
    type: "friendly",
    rating: 4.6,
    reviewCount: 534,
    isOpen: true,
    isPremium: false,
    address: "Lyčkovo náměstí 7, Praha 8 — Karlín",
    district: "Praha 8",
    phone: "+420 222 311 562",
    website: "https://www.spojkakarlin.cz",
    description: "První flexitariánská restaurace v ČR. A la carte menu s veganskými, vegetariánskými, bezlepkovými i masovými jídly, vše v bio kvalitě. Spojuje u jednoho stolu všechny bez předsudků.",
    tags: ["Flexitariánská", "Bio", "Vegan-friendly", "Bezlepkové", "Karlín"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spojka-karlin-flexitarianska-restaurace-praha_5dc99c86.jpg",
    lat: 50.0931,
    lng: 14.4512,
    priceLevel: 2,
    hours: "Po–Pá 11:30–22:00, So–Ne 12:00–22:00",
  },
  {
    id: "23",
    name: "Veganland Express",
    slug: "veganland-express",
    type: "vegan",
    rating: 4.3,
    reviewCount: 267,
    isOpen: true,
    isPremium: false,
    address: "M. Horákové 398, Praha 7 — Letná",
    district: "Praha 7",
    description: "Veganské bistro na Letné se stálou nabídkou i samoobslužným bufetem. Nechybí ani výborné dezerty. Příjemná alternativa pro každodenní veganské stravování.",
    tags: ["Veganská", "Bufet", "Letná", "Dezerty", "S sebou"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganland-express-veganske-bistro-letna_86f24c5d.jpg",
    lat: 50.1001,
    lng: 14.4201,
    priceLevel: 1,
    hours: "Po–Pá 10:00–21:00, So 11:00–20:00",
  },
  {
    id: "24",
    name: "Vegetka",
    slug: "vegetka",
    type: "vegan",
    rating: 4.2,
    reviewCount: 189,
    isOpen: true,
    isPremium: false,
    address: "Kafkova 605/16, Praha 6 — Dejvice",
    district: "Praha 6",
    description: "Veganská restaurace v těsné blízkosti metra A Dejvická. Samoobslužný pult s širokou nabídkou nejen asijské kuchyně. Rychlé a dostupné veganské stravování v Dejvicích.",
    tags: ["Veganská", "Asijská", "Samoobslužný", "Dejvice", "S sebou"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegetka-veganska-restaurace-dejvice_873d2bbd.png",
    lat: 50.1021,
    lng: 14.3921,
    priceLevel: 1,
    hours: "Po–Pá 11:00–18:00, So 11:00–16:00",
  },
  {
    id: "25",
    name: "MyRaw Café",
    slug: "myraw-cafe",
    type: "vegan",
    rating: 4.4,
    reviewCount: 341,
    isOpen: true,
    isPremium: false,
    address: "Na Struze 1739/5, Praha 1 — Nové Město",
    district: "Praha 1",
    description: "Raw veganská kavárna v samém centru Prahy. Specialita na syrovou rostlinnou stravu — raw dezerty, smoothie bowls, čerstvé šťávy a raw hlavní jídla. Ideální pro příznivce raw food.",
    tags: ["Veganská", "Raw food", "Smoothie", "Dezerty", "Kavárna", "Centrum"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/myraw-cafe-raw-veganska-kavarna-praha_94c3f050.png",
    lat: 50.0821,
    lng: 14.4161,
    priceLevel: 2,
    hours: "Po–Ne 9:00–20:00",
  },
  {
    id: "26",
    name: "Chef & Co",
    slug: "chef-and-co",
    type: "vegan",
    rating: 4.3,
    reviewCount: 156,
    isOpen: false,
    isPremium: false,
    address: "Veleslavínova 93/10, Praha 1 — Staré Město",
    district: "Praha 1",
    description: "Restaurace s čistě rostlinnou nabídkou pokrmů v bio kvalitě v centru Prahy. Dočasně uzavřena. Kreativní veganská kuchyně s důrazem na bio suroviny.",
    tags: ["Veganská", "Bio", "Fine dining", "Centrum"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/chef-co-veganske-fine-dining-praha_549b5394.jpg",
    lat: 50.0871,
    lng: 14.4131,
    priceLevel: 3,
    hours: "Dočasně uzavřeno",
  },
  {
    id: "27",
    name: "Loving Bistro Pankrác",
    slug: "loving-bistro-pankrac",
    type: "vegan",
    rating: 4.1,
    reviewCount: 203,
    isOpen: true,
    isPremium: false,
    address: "Na Pankráci 86, Praha 4 — Nusle",
    district: "Praha 4",
    description: "Součást sítě veganských bistr Loving Hut. Veganský způsob stravování jako chutná, zdravá a vyvážená alternativa. Asijská jídla, polévky, saláty a dezerty za dostupné ceny.",
    tags: ["Veganská", "Asijská", "Bufet", "Pankrác", "Dostupné ceny"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/loving-bistro-pankrac-veganske-bistro_38e6d9e6.jpg",
    lat: 50.0631,
    lng: 14.4321,
    priceLevel: 1,
    hours: "Po–Pá 10:30–20:30, So 11:00–20:30",
  },
  {
    id: "28",
    name: "Bistro pod Kavalírkou",
    slug: "bistro-pod-kavalirkou",
    type: "vegan",
    rating: 4.5,
    reviewCount: 87,
    isOpen: false,
    isPremium: false,
    address: "Pod Kavalírkou 471/38, Praha 5 — Košíře",
    district: "Praha 5",
    description: "Rostlinné bistro v Košířích s pestrou kuchyní, skvělými dezerty a různými nápoji. Útulné místo pro milovníky rostlinné stravy mimo centrum.",
    tags: ["Veganská", "Rostlinná strava", "Dezerty", "Košíře"],
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/bistro-pod-kavalirkou-rostlinne-bistro-kosire_6febc750.jpg",
    lat: 50.0701,
    lng: 14.3901,
    priceLevel: 1,
    hours: "Dočasně uzavřeno",
  },
];

const RECIPE_PLACEHOLDER = "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/recipe-hero-kAEk42WS8auJkLKnU8C6NV.webp";

export const recipes: Recipe[] = [
  {
    id: "r1",
    title: "Veganská svíčková na smetaně",
    slug: "veganska-svickova",
    category: "Hlavní jídla",
    prepTime: 30,
    cookTime: 90,
    servings: 4,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-svickova-na-smetane-hlavni-jidlo_2614da46.jpg",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-svickova-na-smetane-hlavni-jidlo_2614da46.jpg", alt: "Veganská svíčková na smetaně — hotové jídlo se seitanem, houskový knedlík a brusinkový dresink" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-svickova-kremova-omacka-detail_1fe82997.jpg", alt: "Detail krémové omáčky veganské svíčkové z kořenové zeleniny" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/veganska-svickova-suroviny-priprava_9bdb24fd.jpg", alt: "Suroviny na veganskou svíčkovou — kořenová zelenina, seitan, kešu ořechy a brusinky" },
    ],
    description: "Klasická česká svíčková v rostlinné verzi. Seitan místo hovězího, cashew smetana a tradiční omáčka z kořenové zeleniny.",
    tags: ["Česká kuchyně", "Seitan", "Tradiční"],
    isVegan: true,
  },
  {
    id: "r2",
    title: "Čočková polévka s uzenou paprikou",
    slug: "cocková-polevka-uzena-paprika",
    category: "Polévky",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cockova-polevka-uzena-paprika-miska_8da21fd8.jpg",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cockova-polevka-uzena-paprika-miska_8da21fd8.jpg", alt: "Miska čočkové polévky s uzenou paprikou a chlebem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cockova-polevka-detail-textura-cocky_397dd7e9.jpg", alt: "Detail textury čočkové polévky s bylinkami a olivovým olejem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cockova-polevka-suroviny-na-stole_864a01cd.jpg", alt: "Suroviny na čočkovou polévku — červená čočka, uzená paprika, cibule a rajčata" },
    ],
    description: "Hustá a výživná čočková polévka s kouřovým aroma uzené papriky. Ideální na chladné dny.",
    tags: ["Polévka", "Čočka", "Rychlé"],
    isVegan: true,
  },
  {
    id: "r3",
    title: "Buddha bowl s pečenou zeleninou",
    slug: "buddha-bowl-pecena-zelenina",
    category: "Saláty a misky",
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/buddha-bowl-pecena-zelenina-barevna-miska_97d30037.jpg",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/buddha-bowl-pecena-zelenina-barevna-miska_97d30037.jpg", alt: "Barevná buddha bowl miska s pečenou zeleninou, quinoou a avokádem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/buddha-bowl-detail-textury-zeleniny_00d33332.jpg", alt: "Detail textur buddha bowlu — křupavá cizrna, krémové avokádo a pečená zelenina" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/buddha-bowl-priprava-ingredience_87630686.jpg", alt: "Příprava ingrediencí na buddha bowl — misky s quinoou, zeleninou a tahini" },
    ],
    description: "Barevná miska plná výživy — quinoa, pečená zelenina, avokádo, cizrna a tahini dresink.",
    tags: ["Bowl", "Quinoa", "Zdravé"],
    isVegan: true,
  },
  {
    id: "r4",
    title: "Veganský guláš s knedlíky",
    slug: "vegansky-gulas-knedliky",
    category: "Hlavní jídla",
    prepTime: 20,
    cookTime: 60,
    servings: 4,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-gulas-s-knedliky-cesky-talir_bfcd04f6.jpg",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-gulas-s-knedliky-cesky-talir_bfcd04f6.jpg", alt: "Veganský guláš s houskovými knedlíky na tradičním českém talíři" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-gulas-detail-omacka-houby_63b3a98b.jpg", alt: "Detail paprikové omáčky veganského guláše s houbami a seitanem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/vegansky-gulas-suroviny-na-dreve_343b5850.jpg", alt: "Suroviny na veganský guláš — houby, seitan, paprika, cibule a kmín" },
    ],
    description: "Tradiční český guláš bez masa — houby a seitan v bohaté paprikové omáčce s domácími houskových knedlíky.",
    tags: ["Česká kuchyně", "Guláš", "Tradiční"],
    isVegan: true,
  },
  {
    id: "r5",
    title: "Špenátové palačinky s tofu ricottou",
    slug: "spenatove-palacinkys-tofu-ricottou",
    category: "Snídaně",
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-palacinky-tofu-ricotta-talir_a1a00801.jpg",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-palacinky-tofu-ricotta-talir_a1a00801.jpg", alt: "Špenátové palačinky plněné tofu ricottou na bílém talíři" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-palacinky-detail-naplne_36e3799d.jpg", alt: "Detail krémové tofu ricotta náplně uvnitř špenátové palačinky" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/spenatove-palacinky-priprava-kuchyne_2f15af24.jpg", alt: "Příprava špenátových palačinek v kuchyni — pánev, špenát a tofu ricotta" },
    ],
    description: "Zelené špenátové palačinky plněné krémovou tofu ricottou s citronem a čerstvými bylinkami.",
    tags: ["Snídaně", "Palačinky", "Špenát"],
    isVegan: true,
  },
  {
    id: "r6",
    title: "Houbové rizoto s parmezánem z kešu",
    slug: "houbove-rizoto-kešu-parmezan",
    category: "Hlavní jídla",
    prepTime: 10,
    cookTime: 35,
    servings: 3,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-kesu-parmezan-servir_34a5ea66.jpg",
    images: [
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-kesu-parmezan-servir_34a5ea66.jpg", alt: "Houbové rizoto s veganským parmezánem z kešu ořechů a čerstvým tymiánem" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-detail-houby-kremove_543a4dc6.jpg", alt: "Detail krémového houbového rizota s plátky lesních hub" },
      { url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/houbove-rizoto-suroviny-ingredience_0647f571.jpg", alt: "Suroviny na houbové rizoto — arborio rýže, lesní houby, kešu ořechy a tymián" },
    ],
    description: "Krémové rizoto s lesními houbami a domácím veganským parmezánem z kešu ořechů.",
    tags: ["Italská", "Rizoto", "Houby"],
    isVegan: true,
  },
];

export const districts = [
  "Všechny čtvrti",
  "Praha 1",
  "Praha 2",
  "Praha 3",
  "Praha 5",
  "Praha 7",
];

export const cuisineTags = [
  "Česká kuchyně",
  "Asijská",
  "Italská",
  "Indická",
  "Vietnamská",
  "Mezinárodní",
  "Organická",
  "Raw",
  "Snídaně",
  "Pekárna",
];

export const getTypeLabel = (type: RestaurantType): string => {
  switch (type) {
    case "vegan": return "Veganská restaurace";
    case "vegetarian": return "Vegetariánská restaurace";
    case "friendly": return "Vegan-friendly";
  }
};

export const getTypeColor = (type: RestaurantType): string => {
  switch (type) {
    case "vegan": return "bg-emerald-700 text-white";
    case "vegetarian": return "bg-emerald-500 text-white";
    case "friendly": return "bg-amber-400 text-amber-900";
  }
};

export const renderStars = (rating: number): { filled: number; half: boolean; empty: number } => {
  const filled = Math.floor(rating);
  const half = rating % 1 >= 0.5;
  const empty = 5 - filled - (half ? 1 : 0);
  return { filled, half, empty };
};
