// ============================================================
// BEZMASAJIDLA.CZ — Recipe Inventory Expansion Dataset
// High-authority plant-based recipes with protein scores & cost estimations.
// ============================================================

import { type Recipe } from "./data";

export const expansionRecipes: Recipe[] = [
  {
    id: "exp_101",
    title: "Tradiční veganská svíčková na smetaně z kořenové zeleniny",
    slug: "tradincni-veganska-svickova-na-smetane",
    category: "Hlavní jídla",
    prepTime: 25,
    cookTime: 45,
    servings: 4,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/svickova-bez-masa_c417c073.webp",
    images: [
      {
        url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/svickova-bez-masa_c417c073.webp",
        alt: "Veganská svíčková na smetaně s houskovým knedlíkem a brusinkami",
      },
    ],
    description: "Krémová česká svíčková ze svižně opékané mrkve, petržele a celeru zjemněná ovesnou smetanou. Podávaná s uzeným tofu a brusinkami.",
    tags: ["Česká klasika", "Tradiční", "High-Protein", "Nedělní oběd", "Svíčková"],
    isVegan: true,
    isGlutenFree: false,
    cuisine: "Česká bezmasá",
    dietaryOptions: ["bio", "high-protein"],
    storyTitle: "Česká svíčková v rostlinném podání",
    story: [
      "Svíčková omáčka je klenotem české gastronomie. Její tajemství nejsvědomitěji spočívá v dokonalé rovnováze sladké kořenové zeleniny, citrónové šťávy a divokého koření.",
      "V naší bezmasé verzi nahrazujeme hovězí maso marinovaným a zauzeným tofu nebo seitanovými plátky, které do omáčky uvolní správnou umami chuť.",
    ],
    macros: {
      calories: 520,
      protein: 24,
      carbs: 68,
      fiber: 9,
      fat: 16,
    },
    editorialReview: {
      summary: "Dokonale sametová omáčka, která zachovává plnou chuť tradiční české svíčkové bez jediného gramu masa.",
      bestFor: "Rodinné nedělní obědy a milovníky tradiční české kuchyně.",
      highlight: "Ovesná smetana a divoké koření dodají omáčce autentický charakter.",
      rating: 4.9,
    },
  },
  {
    id: "exp_102",
    title: "Krémový čočkový dál s kokosovým mlékem a rýží basmati",
    slug: "kremovy-cockovy-dal-s-kokosovym-mlekem",
    category: "Hlavní jídla",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cockovy-dal-kari_c417c073.webp",
    images: [
      {
        url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/cockovy-dal-kari_c417c073.webp",
        alt: "Krémový indický dál z červené čočky s kokosovým mlékem a čerstvým koriandrem",
      },
    ],
    description: "Hřejivý indický dál z červené čočky, kurkumy, římského kmínu a zázvoru. Rychlé výživné jídlo plné rostlinných bílkovin hotové za 20 minut.",
    tags: ["Indická", "Červená čočka", "Rychlá večeře", "Bezlepkové", "High-Protein"],
    isVegan: true,
    isGlutenFree: true,
    cuisine: "Indická",
    dietaryOptions: ["bezlepkové", "high-protein", "low-carb"],
    storyTitle: "Síla indického dálu pro zdravé trávení",
    story: [
      "Červená čočka se uvaří během 15 minut a nevyžaduje předchozí namáčení. V kombinaci s římským kmínem a zázvorem působí blahodárně na střevní mikrobiotu.",
    ],
    macros: {
      calories: 410,
      protein: 22,
      carbs: 58,
      fiber: 12,
      fat: 11,
    },
    editorialReview: {
      summary: "Nejrychlejší a nejchutnější teplá večeře v chladných dnech s vysokým obsahem proteinu.",
      bestFor: "Rychlý všední oběd nebo lehkou večerní regeneraci.",
      highlight: "Zázvor a garam masala vytvářejí nezaměnitelné aroma.",
      rating: 4.8,
    },
  },
  {
    id: "exp_103",
    title: "Křupavé tofu s arašídovou omáčkou a pečenou brokolicí",
    slug: "krupave-tofu-s-arasidovou-omackou",
    category: "Hlavní jídla",
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/arasidove-tofu_c417c073.webp",
    images: [
      {
        url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/arasidove-tofu_c417c073.webp",
        alt: "Zlatavě opékané tofu obalené v kukuřičném škrobu s krémovou arašídovou omáčkou",
      },
    ],
    description: "Zlatavě křupavé kostky tofu obalené v kukuřičném škrobu, zalité pikantní arašídovou omáčkou s tamari sójovkou, limetkou a jasmínovou rýží.",
    tags: ["Tofu", "Asijská", "High-Protein", "Fitness", "Rychlá večeře"],
    isVegan: true,
    isGlutenFree: true,
    cuisine: "Asijská",
    dietaryOptions: ["bezlepkové", "high-protein"],
    macros: {
      calories: 540,
      protein: 28,
      carbs: 45,
      fiber: 7,
      fat: 24,
    },
    editorialReview: {
      summary: "Absolutní hit pro milovníky asijských chutí. Křupavá textura tofu v kombinaci s krémovým arašídovým máslem.",
      bestFor: "Sportovce hledající vysoký příjem rostlinného proteinu.",
      highlight: "Obalení v kukuřičném škrobu zajistí dokonalou křupavost i bez smažení.",
      rating: 5.0,
    },
  },
  {
    id: "exp_104",
    title: "Domácí krémový hummus s pečenou cizrnou a pita chlebem",
    slug: "domaci-kremovy-hummus-s-pecenou-cizrnou",
    category: "Saláty a misky",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/kremovy-hummus-cizrna_c417c073.webp",
    images: [
      {
        url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/kremovy-hummus-cizrna_c417c073.webp",
        alt: "Sametově jemný hummus zdobený křupavou pečenou cizrnou, olivovým olejem a za'atar kořením",
      },
    ],
    description: "Sametově hladkýblízkovýchodní hummus šlehaný s kvalitní tahini pastou, ledovou vodou a citronem. Zdobený dokřupavá pečenou cizrnou s římským kmínem.",
    tags: ["Cizrna", "Hummus", "Předkrm", "Middle Eastern", "Superfood"],
    isVegan: true,
    isGlutenFree: true,
    cuisine: "Středomořská",
    dietaryOptions: ["bezlepkové", "bio"],
    macros: {
      calories: 380,
      protein: 16,
      carbs: 42,
      fiber: 11,
      fat: 18,
    },
    editorialReview: {
      summary: "Tajný trik s ledovou vodou vytvoří ten nejjemnější hummus, jaký jste kdy ochutnali.",
      bestFor: "Párty občerstvení, svačinu do práce i lehkou letní večeři.",
      highlight: "Za'atar koření a panenský olivový olej dodají autentický charakter.",
      rating: 4.9,
    },
  },
  {
    id: "exp_105",
    title: "Pečená květáková křídla v buffalo omáčce s veganským dipem",
    slug: "pecena-kvetakova-kridla-v-buffalo-omacce",
    category: "Hlavní jídla",
    prepTime: 20,
    cookTime: 25,
    servings: 3,
    difficulty: "střední",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/kvetakova-kridla-buffalo_c417c073.webp",
    images: [
      {
        url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/kvetakova-kridla-buffalo_c417c073.webp",
        alt: "Šťavnatá pečená křídla z květáku obalená v pikantní buffalo omáčce podávaná s veganským ranch dresinkem",
      },
    ],
    description: "Šťavnaté růžičky květáku obalené v kukuřičném těstíčku, upečené dozlatova a promíchané v Pikantní maslové buffalo omáčce s česnekem.",
    tags: ["Květák", "Pikantní", "Snack", "Párty", "Street Food"],
    isVegan: true,
    isGlutenFree: false,
    cuisine: "Americká bezmasá",
    dietaryOptions: ["bio"],
    macros: {
      calories: 320,
      protein: 10,
      carbs: 38,
      fiber: 8,
      fat: 14,
    },
    editorialReview: {
      summary: "Nejpopulárnější rostlinná alternativa ke kuřecím křidélkům. Šťavnatý květák v pikantní marinádě.",
      bestFor: "Sledování sportovních zápasů, párty a večery s přáteli.",
      highlight: "Veganský ranch dresink ze kešu ořechů vyváží pálivost buffalo omáčky.",
      rating: 4.8,
    },
  },
  {
    id: "exp_106",
    title: "Uzený tempeh s těstovinami, krémovou špenátovou omáčkou a kešu",
    slug: "uzen-tempeh-s-testovinami-a-spenatem",
    category: "Hlavní jídla",
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "snadný",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/tempeh-testoviny-spenat_c417c073.webp",
    images: [
      {
        url: "https://d2xsxph8kpxj0f.cloudfront.net/310419663032296198/Aob2jK5cbkwX7S9ZSrk5FR/tempeh-testoviny-spenat_c417c073.webp",
        alt: "Křupavý uzený tempeh opékaný na pánvi s penne těstovinami a jemnou špenátovo-kešu omáčkou",
      },
    ],
    description: "Křupavé plátky uzeného tempehu opékané na olivovém oleji, promíchané s penne těstovinami a jemnou omáčkou ze čerstvého špenátu a kešu ořechů.",
    tags: ["Tempeh", "Těstoviny", "Rychlá večeře", "High-Protein", "Fermentované"],
    isVegan: true,
    isGlutenFree: false,
    cuisine: "Italská bezmasá",
    dietaryOptions: ["high-protein", "bio"],
    macros: {
      calories: 580,
      protein: 29,
      carbs: 62,
      fiber: 8,
      fat: 22,
    },
    editorialReview: {
      summary: "Fermentovaný tempeh přináší výjimečnou uzenou chuť a až 29 g bílkovin v jedné porci.",
      bestFor: "Rychlý oběd po tréninku a vydatnou regenerační večeři.",
      highlight: "Rozmixované kešu ořechy vytvoří krémový základ omáčky bez mléčných výrobků.",
      rating: 4.9,
    },
  },
];
