const RECIPE_IMAGE_ROOT = "/images/recipes";

/**
 * Curated, unique images for the imported recipe collection.
 * Keeping this mapping separate makes duplicate-image audits deterministic.
 */
export const recipeImageOverrides: Record<string, string> = {
  "veganska-michana-vajicka-z-tofu": `${RECIPE_IMAGE_ROOT}/veganska-michana-vajicka-z-tofu.webp`,
  "kynute-livance-v-americkem-duchu": `${RECIPE_IMAGE_ROOT}/kynute-livance-v-americkem-duchu.webp`,
  "pres-noc-namocena-chia-ovesna-kase-s-boruvkami": `${RECIPE_IMAGE_ROOT}/pres-noc-namocena-chia-ovesna-kase-s-boruvkami.webp`,
  "detoxikacni-ovocne-smoothie": `${RECIPE_IMAGE_ROOT}/detoxikacni-ovocne-smoothie.webp`,
  "bramborovy-salat-s-domaci-sojanezou": `${RECIPE_IMAGE_ROOT}/bramborovy-salat-s-domaci-sojanezou.webp`,
  "celozrnny-testovinovy-salat-se-susenymi-rajcaty-a-tofu": `${RECIPE_IMAGE_ROOT}/celozrnny-testovinovy-salat-se-susenymi-rajcaty-a-tofu.webp`,
  "kuskusovy-salat-s-brusinkami-a-mandlemi": `${RECIPE_IMAGE_ROOT}/kuskusovy-salat-s-brusinkami-a-mandlemi.webp`,
  "pohankovy-salat-s-tempehem-a-grilovanou-zeleninou": `${RECIPE_IMAGE_ROOT}/pohankovy-salat-s-tempehem-a-grilovanou-zeleninou.webp`,
  "salat-tabbouleh-z-celozrnneho-bulguru-s-marinovanym-tofu": `${RECIPE_IMAGE_ROOT}/salat-tabbouleh-z-celozrnneho-bulguru-s-marinovanym-tofu.webp`,
  "zeleninovy-salat-s-kremovou-tahini-zalivkou": `${RECIPE_IMAGE_ROOT}/zeleninovy-salat-s-kremovou-tahini-zalivkou.webp`,
  "bagetka-s-uzenym-tofu-a-karamelizovanou-cibulkou": `${RECIPE_IMAGE_ROOT}/bagetka-s-uzenym-tofu-a-karamelizovanou-cibulkou.webp`,
  "psenicno-zitny-chleb-s-pecenou-dyni-a-dresinkem": `${RECIPE_IMAGE_ROOT}/psenicno-zitny-chleb-s-pecenou-dyni-a-dresinkem.webp`,
  "cikrnovy-hummus-na-mnoho-zpusobu": `${RECIPE_IMAGE_ROOT}/cikrnovy-hummus-na-mnoho-zpusobu.webp`,
  "bramboracka-s-lesnimi-houbami": `${RECIPE_IMAGE_ROOT}/bramboracka-s-lesnimi-houbami.webp`,
  "brokolicova-polevka-s-hraskem": `${RECIPE_IMAGE_ROOT}/brokolicova-polevka-s-hraskem.webp`,
  "lehce-pikantni-dynova-polevka-s-dynovym-olejem": `${RECIPE_IMAGE_ROOT}/lehce-pikantni-dynova-polevka-s-dynovym-olejem.webp`,
  "fazolova-polevka-s-veganskym-chorizem": `${RECIPE_IMAGE_ROOT}/fazolova-polevka-s-veganskym-chorizem.webp`,
  "kremova-cizrnova-polevka": `${RECIPE_IMAGE_ROOT}/kremova-cizrnova-polevka.webp`,
  "veganska-kulajda-s-hribky-a-koprem": `${RECIPE_IMAGE_ROOT}/veganska-kulajda-s-hribky-a-koprem.webp`,
  "polevka-ze-sladke-kukurice-s-chilli": `${RECIPE_IMAGE_ROOT}/polevka-ze-sladke-kukurice-s-chilli.webp`,
  "raw-brokolicova-polevka-s-avokadem": `${RECIPE_IMAGE_ROOT}/raw-brokolicova-polevka-s-avokadem.webp`,
  "raw-rajcatova-polevka-s-bazalkou": `${RECIPE_IMAGE_ROOT}/raw-rajcatova-polevka-s-bazalkou.webp`,
  "ryzove-nudle-s-veganskym-kurecim-masem-a-teriyaki": `${RECIPE_IMAGE_ROOT}/ryzove-nudle-s-veganskym-kurecim-masem-a-teriyaki.webp`,
  "veganska-kachna-se-spenatem-a-knedlikem": `${RECIPE_IMAGE_ROOT}/veganska-kachna-se-spenatem-a-knedlikem.webp`,
  "falafel-a-hummus-v-pita-chlebu": `${RECIPE_IMAGE_ROOT}/falafel-a-hummus-v-pita-chlebu.webp`,
  "grilovana-zelenina-a-tofu-s-hummusovym-dipem": `${RECIPE_IMAGE_ROOT}/grilovana-zelenina-a-tofu-s-hummusovym-dipem.webp`,
  "vegansky-kureci-rizek-s-bramborovou-kasi": `${RECIPE_IMAGE_ROOT}/vegansky-kureci-rizek-s-bramborovou-kasi.webp`,
  "veganske-kureci-spizy-se-tremi-omacami": `${RECIPE_IMAGE_ROOT}/veganske-kureci-spizy-se-tremi-omacami.webp`,
  "musaka-s-lilkem-a-smetanovym-besamelem": `${RECIPE_IMAGE_ROOT}/musaka-s-lilkem-a-smetanovym-besamelem.webp`,
  "osso-buco-z-marinovaneho-tofu": `${RECIPE_IMAGE_ROOT}/osso-buco-z-marinovaneho-tofu.webp`,
  "veganske-krevety-se-zeleninou": `${RECIPE_IMAGE_ROOT}/veganske-krevety-se-zeleninou.webp`,
  "vegansky-burger-xxl": `${RECIPE_IMAGE_ROOT}/vegansky-burger-xxl.webp`,
  "ratatouille-s-ryzi-basmati": `${RECIPE_IMAGE_ROOT}/ratatouille-s-ryzi-basmati.webp`,
  "raw-pohankovy-salat-s-kremem-z-kesu": `${RECIPE_IMAGE_ROOT}/raw-pohankovy-salat-s-kremem-z-kesu.webp`,
  "raw-bolonske-lasagne-s-kvetakem": `${RECIPE_IMAGE_ROOT}/raw-bolonske-lasagne-s-kvetakem.webp`,
  "raw-tabbouleh-salat-s-quinoou": `${RECIPE_IMAGE_ROOT}/raw-tabbouleh-salat-s-quinoou.webp`,
  "raw-tatarak-z-cervene-repy": `${RECIPE_IMAGE_ROOT}/raw-tatarak-z-cervene-repy.webp`,
  "rajcata-plnena-kesu-kremem": `${RECIPE_IMAGE_ROOT}/rajcata-plnena-kesu-kremem.webp`,
  "veganske-kure-na-paprice-s-testovinami": `${RECIPE_IMAGE_ROOT}/veganske-kure-na-paprice-s-testovinami.webp`,
  "bezlepkovy-spenatovy-quiche-s-tofu": `${RECIPE_IMAGE_ROOT}/bezlepkovy-spenatovy-quiche-s-tofu.webp`,
  "plnene-bramborove-knedliky-s-uzenym-tofu": `${RECIPE_IMAGE_ROOT}/plnene-bramborove-knedliky-s-uzenym-tofu.webp`,
  "cocka-s-korenovou-zeleninou": `${RECIPE_IMAGE_ROOT}/cocka-s-korenovou-zeleninou.webp`,
  "smoothie-pro-chladne-rano": `${RECIPE_IMAGE_ROOT}/smoothie-pro-chladne-rano.webp`,
  "smoothie-pro-letni-rano": `${RECIPE_IMAGE_ROOT}/smoothie-pro-letni-rano.webp`,
  "sport-smoothie-s-proteinem": `${RECIPE_IMAGE_ROOT}/sport-smoothie-s-proteinem.webp`,
  "letni-exoticke-smoothie": `${RECIPE_IMAGE_ROOT}/letni-exoticke-smoothie.webp`,
  "smoothie-pro-lepsi-imunitu": `${RECIPE_IMAGE_ROOT}/smoothie-pro-lepsi-imunitu.webp`,
  "domaci-konopne-mleko": `${RECIPE_IMAGE_ROOT}/domaci-konopne-mleko.webp`,
  "cokoladovy-kolac-z-polenty": `${RECIPE_IMAGE_ROOT}/cokoladovy-kolac-z-polenty.webp`,
  "jahlovy-kolac-s-vuni-podzimu": `${RECIPE_IMAGE_ROOT}/jahlovy-kolac-s-vuni-podzimu.webp`,
  "celozrnny-makovec": `${RECIPE_IMAGE_ROOT}/celozrnny-makovec.webp`,
  "raw-boruvkovy-cheesecake": `${RECIPE_IMAGE_ROOT}/raw-boruvkovy-cheesecake.webp`,
  "malinova-zmrzlina-s-ruzovou-slehackou": `${RECIPE_IMAGE_ROOT}/malinova-zmrzlina-s-ruzovou-slehackou.webp`,
  "coko-boruvkove-proteinove-tycinky": `${RECIPE_IMAGE_ROOT}/coko-boruvkove-proteinove-tycinky.webp`,
  "ruzovy-kolac-s-cokoladovym-kremem": `${RECIPE_IMAGE_ROOT}/ruzovy-kolac-s-cokoladovym-kremem.webp`,
  "pohankove-livance-s-jahodami": `${RECIPE_IMAGE_ROOT}/pohankove-livance-s-jahodami.webp`,
  "avokadovy-puding-s-chia-seminkem": `${RECIPE_IMAGE_ROOT}/avokadovy-puding-s-chia-seminkem.webp`,
  "amarantove-kulicky-se-skorici": `${RECIPE_IMAGE_ROOT}/amarantove-kulicky-se-skorici.webp`,
  "minne-di-sant-agata-sicilske-kolacky": `${RECIPE_IMAGE_ROOT}/minne-di-sant-agata-sicilske-kolacky.webp`,
};
